// ── MenuItemTile component (todo-refactor-kds-agents-3.md) ──────────────
//
// A single product tile in the restaurant menu grid: name, price, optional
// pin badge, and the add/added/unavailable badge — one native button. Owns
// the touch long-press → context-menu gesture and its click-suppression
// rules; delegates adding and context-menu opening to props.
//
// Invariants:
//   - `product.inStock` already folds in the local 86/unavailable override;
//     `sourceInStock` carries the catalog value so the context menu only
//     offers the availability toggle for source-in-stock items.
//   - A completed long-press suppresses its synthetic click, and any newer
//     pointer or keyboard sequence clears that suppression.
//   - The `restaurant-card*` class names and DOM shape are pinned by
//     RestaurantMenu.test.tsx and restaurantCardHeight.test.ts — never
//     rename them here.

import { useCallback, useEffect, useRef } from 'react';
import { requiredLocalized } from '@/frontend/shared';
import { Localized } from '@/components/Localized';
import { formatMoney, type Product } from '@/types/domain';
import { useLocalization } from '@fluent/react';

// Allow normal touchscreen finger jitter without mistaking a real drag/scroll
// for a long-press context-menu request.
const TOUCH_SLOP_PX = 8;

/**
 * Add-badge glyphs for the card's accent strip — a filled circle with a
 * plus (default), check (400ms added flash), or minus (unavailable).
 * The circle is a two-tone badge: fill comes from CSS (--color-accent-fg)
 * and the glyph is stroked in --color-accent, so it reads as a button on
 * the coloured strip while keeping contrast in every theme.
 */
type AddGlyph = 'plus' | 'check' | 'minus';

function AddBadge({ glyph }: { glyph: AddGlyph }) {
  return (
    <svg viewBox="0 0 24 24" className="restaurant-card-add-badge" aria-hidden="true">
      <circle cx="12" cy="12" r="10" />
      {glyph === 'plus' && <path d="M12 8v8M8 12h8" />}
      {glyph === 'check' && <path d="M8.5 12.5l2.5 2.5 4.5-5" />}
      {glyph === 'minus' && <path d="M8 12h8" />}
    </svg>
  );
}

// ── Pin icon SVG ──────────────────────────────────────────────────

function PinIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" width="12" height="12" aria-hidden="true">
      <path d="M16 12V4h1V2H7v2h1v8l-2 2v2h5.2v6h1.6v-6H18v-2l-2-2z" />
    </svg>
  );
}

// ── Component ─────────────────────────────────────────────────────

export interface MenuItemTileProps {
  product: Product;
  sourceInStock: boolean;
  pinned: boolean;
  color: string | undefined;
  onAdd: ((product: Product) => void) | undefined;
  onContextMenu: (sku: string, e: React.MouseEvent, trigger: HTMLElement, fromKeyboard: boolean, sourceInStock: boolean) => void;
  added?: boolean;
  index?: number;
}

export function MenuItemTile({ product, sourceInStock, pinned, color, onAdd, onContextMenu, added, index }: MenuItemTileProps) {
  const { l10n } = useLocalization();
  const touchLongPressTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const touchStartRef = useRef<{ x: number; y: number } | null>(null);
  const suppressClickRef = useRef(false);
  const productRef = useRef(product);
  productRef.current = product;
  const onContextMenuRef = useRef(onContextMenu);
  onContextMenuRef.current = onContextMenu;

  const unavailableLabel = requiredLocalized(l10n, 'restaurant-card-unavailable');
  const addLabel = requiredLocalized(l10n, 'restaurant-card-add');
  const cardAriaLabel = product.inStock
    ? `${product.name}, ${formatMoney(product.price)}, ${addLabel}`
    : `${product.name}, ${formatMoney(product.price)}, ${unavailableLabel}`;

  const clearTouchLongPress = useCallback(() => {
    if (touchLongPressTimerRef.current) {
      clearTimeout(touchLongPressTimerRef.current);
      touchLongPressTimerRef.current = null;
    }
    touchStartRef.current = null;
  }, []);

  const handleClick = useCallback(() => {
    if (suppressClickRef.current) {
      // The synthetic click generated by a long-press is suppressed, but a
      // later pointer sequence clears this flag in handlePointerDown.
      suppressClickRef.current = false;
      return;
    }
    // Source-unavailable cards remain context-menu accessible for pin/color
    // actions, but must never add an out-of-stock item to the sale.
    if (!product.inStock) return;
    onAdd?.(product);
  }, [product, onAdd]);

  const handleContext = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    onContextMenu(product.sku, e, e.currentTarget as HTMLElement, false, sourceInStock);
  }, [product.sku, sourceInStock, onContextMenu]);

  const handlePointerDown = useCallback((e: React.PointerEvent<HTMLButtonElement>) => {
    // A long-press may not produce the browser's synthetic click after the
    // context menu opens. Clear suppression when a new pointer sequence starts
    // so the next deliberate tap can never be swallowed.
    suppressClickRef.current = false;
    if (e.pointerType && e.pointerType !== 'touch') return;
    clearTouchLongPress();
    touchStartRef.current = { x: e.clientX, y: e.clientY };
    const trigger = e.currentTarget;
    touchLongPressTimerRef.current = setTimeout(() => {
      suppressClickRef.current = true;
      const rect = trigger.getBoundingClientRect();
      const clientX = Number.isFinite(e.clientX) ? e.clientX : rect.left + rect.width / 2;
      const clientY = Number.isFinite(e.clientY) ? e.clientY : rect.top + rect.height / 2;
      onContextMenuRef.current(
        productRef.current.sku,
        {
          preventDefault: () => {},
          clientX: Number.isFinite(clientX) ? clientX : 4,
          clientY: Number.isFinite(clientY) ? clientY : 4,
        } as unknown as React.MouseEvent,
        trigger,
        false,
        sourceInStock,
      );
      touchLongPressTimerRef.current = null;
    }, 500);
  }, [clearTouchLongPress, sourceInStock]);

  const handlePointerMove = useCallback((e: React.PointerEvent<HTMLButtonElement>) => {
    if (!touchStartRef.current || (e.pointerType && e.pointerType !== 'touch')) return;

    const dx = e.clientX - touchStartRef.current.x;
    const dy = e.clientY - touchStartRef.current.y;
    // Ignore small coordinate jitter from a resting finger. Cancel only when
    // movement exceeds the touch slop, which indicates scrolling or dragging.
    // If a WebView omits coordinates, keep the timer alive rather than
    // cancelling a valid long-press on an indeterminate movement event.
    if (!Number.isFinite(dx) || !Number.isFinite(dy) || Math.hypot(dx, dy) <= TOUCH_SLOP_PX) return;
    clearTouchLongPress();
  }, [clearTouchLongPress]);

  const handlePointerUp = useCallback((e: React.PointerEvent<HTMLButtonElement>) => {
    if (!e.pointerType || e.pointerType === 'touch') clearTouchLongPress();
  }, [clearTouchLongPress]);

  const handlePointerLeave = useCallback((e: React.PointerEvent<HTMLButtonElement>) => {
    if (!e.pointerType || e.pointerType === 'touch') clearTouchLongPress();
  }, [clearTouchLongPress]);

  useEffect(() => () => clearTouchLongPress(), [clearTouchLongPress]);

  const handleKeyDown = useCallback((e: React.KeyboardEvent<HTMLButtonElement>) => {
    // A keyboard activation starts a distinct interaction sequence. Clear any
    // stale touch suppression so a long-press cannot swallow Enter or Space.
    if (e.key === 'Enter' || e.key === ' ') {
      suppressClickRef.current = false;
    }
    if (e.key === 'ContextMenu' || (e.shiftKey && e.key === 'F10')) {
      e.preventDefault();
      const rect = e.currentTarget.getBoundingClientRect();
      onContextMenu(
        product.sku,
        {
          preventDefault: () => {},
          clientX: rect.right,
          clientY: rect.top,
        } as unknown as React.MouseEvent,
        e.currentTarget,
        true,
        sourceInStock,
      );
    }
  }, [product.sku, sourceInStock, onContextMenu]);

  let cardClass = 'restaurant-card';
  if (pinned) cardClass += ' restaurant-card--pinned';
  if (!product.inStock) cardClass += ' restaurant-card--disabled';
  if (added) cardClass += ' restaurant-card--added';

  return (
    <button
      type="button"
      className={cardClass}
      tabIndex={0}
      aria-disabled={!product.inStock}
      onClick={handleClick}
      onContextMenu={handleContext}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
      onPointerCancel={handlePointerUp}
      onPointerLeave={handlePointerLeave}
      onKeyDown={handleKeyDown}
      aria-label={cardAriaLabel}
      style={{
        '--btn-color': color ?? 'var(--color-accent)',
        animationDelay: `${(index ?? 0) * 35}ms`,
      } as React.CSSProperties}
    >
      <div className="restaurant-card-body">
        {pinned && (
          <span className="restaurant-card-pin-badge" title={requiredLocalized(l10n, 'restaurant-card-pin-title')}>
            <PinIcon />
          </span>
        )}
        <span className="restaurant-card-name" title={product.name}>
          {product.name}
        </span>
        <span className="restaurant-card-price">{formatMoney(product.price)}</span>
        {!product.inStock && (
          <span className="restaurant-card-status">
            <Localized id="restaurant-card-unavailable"><span>Unavailable</span></Localized>
          </span>
        )}
      </div>
      {product.inStock ? (
        <span className="restaurant-card-add-icon">
          <AddBadge glyph={added ? 'check' : 'plus'} />
          <span className="sr-only">
            <Localized id="restaurant-card-add">
              <span>Add</span>
            </Localized>
          </span>
        </span>
      ) : (
        <span className="restaurant-card-add-icon restaurant-card-add-icon--disabled" aria-hidden="true">
          <AddBadge glyph="minus" />
        </span>
      )}
    </button>
  );
}
