//! GENERATED by the registration-gate sweep - DO NOT HAND-EDIT. //!
//!
//! Every registered command this shell gate-accepts is absent from this file;
//! everything it does not accept appears once, with the measured state:
//! "no_session_resolution" (the wrapper never resolves a session) or
//! "resolves_session_names_no_permission" (it resolves one and asks nobody whether
//! the caller may - authenticate-then-assume).

//! Regenerate rather than type: see the header of registration_gate_tests.rs.
//! A hand-edited line here is the drift this generated file exists to prevent.

/// The measured debt ledger: (registered name, state).
pub const DEBT_LEDGER: &[(&str, &str)] = &[
    ("auth::staff_login", "no_session_resolution"),
    ("auth::staff_check_username", "no_session_resolution"),
    ("auth::has_users", "no_session_resolution"),
    ("auth::create_session", "no_session_resolution"),
    ("auth::list_organizations", "no_session_resolution"),
    ("branding::get_brand_settings", "no_session_resolution"),
    ("branding::pick_logo_file", "no_session_resolution"),
    ("data::get_backup_status", "no_session_resolution"),
    ("data::create_backup", "no_session_resolution"),
    ("email::get_report_schedule", "no_session_resolution"),
    ("edc::edc_terminal_status", "no_session_resolution"),
    ("staff::bootstrap_owner", "no_session_resolution"),
    ("currencies::currency_info", "no_session_resolution"),
    (
        "currencies::currency_info_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "currencies::list_currencies_scoped",
        "resolves_session_names_no_permission",
    ),
    ("currencies::get_default_currency", "no_session_resolution"),
    (
        "currencies::get_default_currency_scoped",
        "resolves_session_names_no_permission",
    ),
    ("currencies::set_default_currency", "no_session_resolution"),
    (
        "currencies::set_default_currency_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::list_exchange_rates_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::list_latest_exchange_rates_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::create_exchange_rate_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::delete_exchange_rate_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::get_latest_exchange_rate_scoped",
        "resolves_session_names_no_permission",
    ),
    ("features::list_all_features", "no_session_resolution"),
    ("health::ping", "no_session_resolution"),
    (
        "health::ping_scoped",
        "resolves_session_names_no_permission",
    ),
    ("health::version", "no_session_resolution"),
    (
        "health::version_scoped",
        "resolves_session_names_no_permission",
    ),
    ("health::get_device_id", "no_session_resolution"),
    (
        "health::get_device_id_scoped",
        "resolves_session_names_no_permission",
    ),
    ("health::get_local_ip", "no_session_resolution"),
    (
        "health::get_local_ip_scoped",
        "resolves_session_names_no_permission",
    ),
    ("settings::set_setting", "no_session_resolution"),
    ("setup::get_enabled_features", "no_session_resolution"),
    ("setup::complete_setup", "no_session_resolution"),
    ("setup::dismiss_setup_wizard", "no_session_resolution"),
    (
        "browser::open_product_images_scoped",
        "resolves_session_names_no_permission",
    ),
    ("setup::get_setup_status", "no_session_resolution"),
    ("security::get_key_rotation_info", "no_session_resolution"),
    ("security::rotate_encryption_key", "no_session_resolution"),
    ("workspaces::list_workspaces", "no_session_resolution"),
    (
        "workspaces::list_workspace_screens",
        "no_session_resolution",
    ),
    ("workspaces::resolve_boot_store", "no_session_resolution"),
    ("license::activate_license", "no_session_resolution"),
    ("license::get_machine_id", "no_session_resolution"),
    ("license::get_hardware_fingerprint", "no_session_resolution"),
    ("license::renew_license", "no_session_resolution"),
    ("license::pause_subscription", "no_session_resolution"),
    ("license::resume_subscription", "no_session_resolution"),
    ("license::get_license_status", "no_session_resolution"),
    ("license::check_license_status", "no_session_resolution"),
    ("license::test_auth_connection", "no_session_resolution"),
    (
        "subscription::get_subscription_capabilities",
        "no_session_resolution",
    ),
    ("topology::load_topology", "no_session_resolution"),
    (
        "topology::can_save_topology",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::apply_topology_diff",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::list_topology_revisions",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::load_topology_revision",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::pin_topology_revision",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::save_topology_template",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::load_topology_template",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::list_topology_templates",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::delete_topology_template",
        "resolves_session_names_no_permission",
    ),
    ("settings::get_setting", "no_session_resolution"),
    ("settings::gateway_status", "no_session_resolution"),
    (
        "scale::read_scale_weight_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "scale::list_scale_devices_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "sync::pg_sync_status_scoped",
        "resolves_session_names_no_permission",
    ),
    ("sync::test_sync_connection", "no_session_resolution"),
];

/// Registered commands the sweep found today. The floor in
/// registration_gate_tests.rs is asserted equal to this, so a regenerated ledger
/// that disagrees with a hand-kept floor fails the build.
pub const REGISTERED_TOTAL: usize = 448;

/// Debt entries today: the ceiling the ledger may only shrink under.
pub const DEBT_CEILING: usize = 70;

/// Names that never resolve a session at all.
pub const NO_SESSION_RESOLUTION: usize = 44;

/// Authenticate-then-assume: a session is resolved and no permission asked.
pub const RESOLVES_SESSION_NAMES_NO_PERMISSION: usize = 26;

/// Registered names whose wrapper body the generator could not find (must be 0).
pub const UNSOURCED: usize = 0;
