//! GENERATED by the registration-gate sweep - DO NOT HAND-EDIT. //!
//!
//! Every registered command this shell gate-accepts is absent from this file;
//! everything it does not accept appears once, with the measured state:
//! "no_session_resolution" (the wrapper never resolves a session) or
//! "resolves_session_names_no_permission" (it resolves one and asks nobody whether
//! the caller may - authenticate-then-assume).

//! Regenerate rather than type: see the header of registration_gate_tests.rs.
//! A hand-edited line here is the drift this generated file exists to prevent.

/// The measured debt ledger: (registered name, state).
pub const DEBT_LEDGER: &[(&str, &str)] = &[
    ("auth::staff_login", "no_session_resolution"),
    ("auth::staff_check_username", "no_session_resolution"),
    ("auth::has_users", "no_session_resolution"),
    ("auth::create_session", "no_session_resolution"),
    ("auth::list_organizations", "no_session_resolution"),
    ("branding::get_brand_settings", "no_session_resolution"),
    ("branding::pick_logo_file", "no_session_resolution"),
    ("data::get_backup_status", "no_session_resolution"),
    ("data::create_backup", "no_session_resolution"),
    ("data::export_data_without_session", "no_session_resolution"),
    ("email::get_report_schedule", "no_session_resolution"),
    ("edc::edc_terminal_status", "no_session_resolution"),
    ("staff::bootstrap_owner", "no_session_resolution"),
    ("currencies::currency_info", "no_session_resolution"),
    (
        "currencies::currency_info_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "currencies::list_currencies_scoped",
        "resolves_session_names_no_permission",
    ),
    ("currencies::get_default_currency", "no_session_resolution"),
    (
        "currencies::get_default_currency_scoped",
        "resolves_session_names_no_permission",
    ),
    ("currencies::set_default_currency", "no_session_resolution"),
    (
        "currencies::set_default_currency_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::list_exchange_rates_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::list_latest_exchange_rates_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::create_exchange_rate_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::delete_exchange_rate_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "exchange_rates::get_latest_exchange_rate_scoped",
        "resolves_session_names_no_permission",
    ),
    ("features::list_all_features", "no_session_resolution"),
    ("health::ping", "no_session_resolution"),
    (
        "health::ping_scoped",
        "resolves_session_names_no_permission",
    ),
    ("health::version", "no_session_resolution"),
    (
        "health::version_scoped",
        "resolves_session_names_no_permission",
    ),
    ("health::get_device_id", "no_session_resolution"),
    (
        "health::get_device_id_scoped",
        "resolves_session_names_no_permission",
    ),
    ("health::get_local_ip", "no_session_resolution"),
    (
        "health::get_local_ip_scoped",
        "resolves_session_names_no_permission",
    ),
    ("settings::set_setting", "no_session_resolution"),
    ("setup::get_enabled_features", "no_session_resolution"),
    ("setup::get_first_run_state", "no_session_resolution"),
    ("setup::provision_device", "no_session_resolution"),
    (
        "browser::open_product_images_scoped",
        "resolves_session_names_no_permission",
    ),
    ("security::get_key_rotation_info", "no_session_resolution"),
    ("workspaces::list_workspaces", "no_session_resolution"),
    (
        "workspaces::list_workspace_screens",
        "no_session_resolution",
    ),
    ("workspaces::resolve_boot_store", "no_session_resolution"),
    ("license::activate_license", "no_session_resolution"),
    ("desktop_link::link_device_google", "no_session_resolution"),
    (
        "desktop_link::link_device_email_request",
        "no_session_resolution",
    ),
    (
        "desktop_link::link_device_email_consume",
        "no_session_resolution",
    ),
    ("license::get_machine_id", "no_session_resolution"),
    ("license::get_hardware_fingerprint", "no_session_resolution"),
    ("license::renew_license", "no_session_resolution"),
    ("license::pause_subscription", "no_session_resolution"),
    ("license::resume_subscription", "no_session_resolution"),
    ("license::get_license_status", "no_session_resolution"),
    ("license::check_license_status", "no_session_resolution"),
    ("license::test_auth_connection", "no_session_resolution"),
    (
        "subscription::get_subscription_capabilities",
        "no_session_resolution",
    ),
    (
        "topology::load_topology",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::can_save_topology",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::apply_topology_diff",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::list_topology_revisions",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::load_topology_revision",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::pin_topology_revision",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::save_topology_template",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::load_topology_template",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::list_topology_templates",
        "resolves_session_names_no_permission",
    ),
    (
        "topology::delete_topology_template",
        "resolves_session_names_no_permission",
    ),
    ("settings::get_setting", "no_session_resolution"),
    ("settings::gateway_status", "no_session_resolution"),
    (
        "scale::read_scale_weight_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "scale::list_scale_devices_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "sync::pg_sync_status_scoped",
        "resolves_session_names_no_permission",
    ),
    ("sync::test_sync_connection", "no_session_resolution"),
];

/// Registered commands the sweep found today — measured by `run_sweep` and written here by
/// the generator, which is why it now reads 461 rather than the 447 that once lagged inside
/// `REGISTERED_SLACK`. It is NOT the pin: the floor in registration_gate_tests.rs is
/// measured from the tree itself, and a number here that falls behind means a regeneration
/// is overdue rather than that a build will fail. (Corrected 18-09-26 with the generator;
/// this comment described the earlier ledger-versus-ledger comparison the floor leg
/// replaced. Re-read 20-09-26: regenerated with the floor's raise to 458, then to 461 with
/// the emailed-code pair's arrival — the floor moved in the same pass both times, because
/// the generator writing this number does not move it.)
pub const REGISTERED_TOTAL: usize = 461;

/// Debt entries today: the ceiling the ledger may only shrink under.
/// 70 -> 69: `security::rotate_encryption_key` was deregistered, and its ledger row
/// left in the same commit that moved this number. That coupling is the only way a
/// ceiling is allowed to go down.
/// 69 -> 72: RAISED by the device-link half of ADR #54, the first rise in this file.
/// `desktop_link::link_device_google`, `link_device_email_request` and
/// `link_device_email_consume` all arrived in class 1 (`no_session_resolution`), so the
/// measured count went 69 -> 72 and the ledger grew by the same three rows. Class 1 is
/// STRUCTURAL here rather than an omission: the wizard's account step runs before any
/// staff session exists and the device authenticates to the licence server with its own
/// stored credentials, so a session permission would guard a door no session can reach —
/// the same class `license::activate_license` has always occupied. Recorded in
/// docs/records/JOURNAL.md, which is what the ceiling pin asks of a rise.
pub const DEBT_CEILING: usize = 72;

/// Names that never resolve a session at all.
/// 42: `topology::load_topology` now resolves session (moved to class 2, mirroring
/// `load_topology_template`).
/// 42 -> 45: the three `desktop_link::` rows above. This count is a pin the generator
/// does not recompute, so it moved by hand in the same pass as the ceiling.
/// `45 + 27 = 72` partitions `DEBT_CEILING` again.
pub const NO_SESSION_RESOLUTION: usize = 45;

/// Authenticate-then-assume: a session is resolved and no permission asked.
pub const RESOLVES_SESSION_NAMES_NO_PERMISSION: usize = 27;

/// Registered names whose wrapper body the generator could not find (must be 0).
pub const UNSOURCED: usize = 0;
