#!/usr/bin/env python3
"""Generate the Postgres port of the FULLY-MIGRATED SQLite schema.

Pipeline (rebuilt 2026-08-31; the old text-based version read only the
frozen 20260813_init.sql and silently diverged from the 14+ incremental
migrations — the drift the loyalty work exposed):

1. Parse the migration registry order from crates/kasirmu-core/src/migrations.rs
   (the canonical source — registry order is NOT plain filename order).
2. Apply every migration to an in-memory SQLite database (python sqlite3,
   needs SQLite >= 3.35 for ALTER TABLE ... DROP COLUMN).
3. Dump the FINAL state: CREATE TABLE / index / trigger text from
   sqlite_master (SQLite keeps it current across ADD/DROP COLUMN), plus
   seed rows from every table that ends up non-empty.
4. Translate to Postgres DDL:

   * ``strftime('%Y-%m-%dT%H:%M:%fZ', 'now')`` → ISO-8601 ``to_char(now() …)``
   * ``datetime('now')`` → ``to_char(now() …)``
   * ``INTEGER`` → ``BIGINT`` (SQLite INTEGER is 64-bit, like Rust ``i64``)
   * ``REAL`` → ``DOUBLE PRECISION``
   * ``INTEGER PRIMARY KEY AUTOINCREMENT`` → ``BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY``
   * ``) STRICT`` table option → dropped (Postgres has no equivalent)
   * seeds → ``INSERT … ON CONFLICT DO NOTHING`` (idempotent re-apply);
     timestamp values that are "now"-derived (column DEFAULT or an
     explicit strftime in the seed INSERT — detected by freshness, see
     _quote) are re-emitted as the PG now-expression so output stays
     deterministic
   * triggers → hand-written plpgsql from TRIGGER_MAP; every dumped
     trigger needs an entry and every entry must be live (fail closed
     both ways — the ERR-10 stale-exemption discipline). That membership
     check is NAME-ONLY: it proves each port EXISTS, never that it MEANS
     the same thing as the SQLite trigger it mirrors. C43 added the
     TRIGGER_VERIFICATION gate (declared test + body digest) as the
     compensating control; for the six older ports the named test pins
     the SQLite trigger rather than executing the plpgsql, and that
     residual gap is stated on that table rather than implied away.
   * RLS appendix → curated RLS_TABLES list (enabling RLS is a policy
     decision: the write path must populate tenant_id); the generator
     fails if an entry loses its table or column, and lists tenant_id
     tables not yet covered as a visible comment — every uncovered
     table must carry a documented reason in RLS_EXEMPT or generation
     fails (coverage debt can neither appear nor vanish silently)

5. Re-emit CREATE TABLE in **topological order** (Kahn over
   ``REFERENCES t(col)``): SQLite tolerates forward FK references,
   Postgres does not.

6. Prepend two convergence sections for databases that already exist,
   because ``CREATE TABLE IF NOT EXISTS`` is inert for COLUMNS and for
   dropped indexes:

   * a guarded column-reconciliation ``DO`` block covering every column
     of every table (add the column when the table pre-exists without it;
     promote to NOT NULL only when no row is NULL). Generated from the
     same final SQLite state as the DDL, so it cannot rot.
   * guarded ``DROP INDEX IF EXISTS`` for ``OBSOLETE_PG_INDEXES`` —
     indexes an earlier revision emitted and a later migration removed,
     which an existing database would otherwise keep forever.

Usage:

    python3 scripts/generate-pg-migration.py           # write the file
    python3 scripts/generate-pg-migration.py --check   # drift guard, writes nothing

--check renders the output twice (two independent migration runs) and
fails on any difference — that is the determinism self-proof — then
compares against the committed file (newline-normalized) and exits 1 on
drift without touching the working tree. CI runs --check; the pre-commit
hook runs it whenever a migration file or this script is staged.
"""

from __future__ import annotations

import hashlib
import re
import sqlite3
import sys
from collections import defaultdict, deque
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIG_DIR = ROOT / "crates" / "kasirmu-core" / "migrations"
REGISTRY_RS = ROOT / "crates" / "kasirmu-core" / "src" / "migrations.rs"
DST = MIG_DIR / "20260813_init.pg.sql"

# ISO-8601 UTC timestamp string, matching SQLite's
# strftime('%Y-%m-%dT%H:%M:%fZ', 'now') output shape.
TS_PG = "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"')"
# SQLite datetime('now') → 'YYYY-MM-DD HH:MM:SS'.
DT_PG = "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"

# Indexes that exist ONLY in the SQLite schema. PostgreSQL cannot build
# them: an expression index on a value derived from a TEXT column via a
# cast (`date(created_at)` / `created_at::date`) is rejected because the
# text→date cast is STABLE (DateStyle-dependent), not IMMUTABLE.
SQLITE_ONLY_INDEXES = {"idx_sales_status_created_date"}

# Indexes an EARLIER revision of this generator emitted and a later SQLite
# migration removed. Postgres has no re-apply for a dropped object: the
# generated script only ever says ``CREATE … IF NOT EXISTS``, so a database
# created before the removal keeps the index forever and silently enforces a
# constraint the current schema does not declare. Each entry is emitted as a
# guarded DROP so an existing database converges on the current schema.
# Value = the SQLite migration that removed it (provenance for the reader).
#
# idx_tax_rates_single_default was ``UNIQUE (is_default) WHERE is_default = 1``
# — at most ONE default tax rate per database. 20260926 replaced it with three
# per-scope partial unique indexes (tenant-global / per legal entity / per
# location), so the stale global index would refuse the second scoped default
# the new model exists to allow.
OBSOLETE_PG_INDEXES: dict[str, str] = {
    "idx_tax_rates_single_default": "20260926_tax_rate_scoped_authoring.sql",
    # 20260906 renamed store_profiles -> locations and user_store_access ->
    # user_location_access and dropped these two by name. A renamed table
    # carries its indexes along, so a database built before the rename keeps
    # them under the old names while the snapshot creates the new ones —
    # leaving two identical partial indexes and two identical user indexes.
    "idx_store_profiles_primary": "20260906_rename_store_to_location.sql",
    "idx_user_store_access_user_id": "20260906_rename_store_to_location.sql",
}

HEADER = """\
-- ====================================================================
-- OZ-POS Database Schema — Postgres port of the fully-migrated SQLite
-- schema (20260813_init.sql + every incremental migration in the
-- crates/kasirmu-core/src/migrations.rs registry, applied and dumped at
-- final state).
-- Generated by scripts/generate-pg-migration.py — DO NOT EDIT BY HAND.
-- Regenerate:  python3 scripts/generate-pg-migration.py
-- Drift guard: python3 scripts/generate-pg-migration.py --check
-- ====================================================================
"""

# Hand-written Postgres equivalents of the SQLite triggers, keyed by
# trigger name. The generator fails closed if the dumped set and this
# map ever disagree (missing port OR stale entry).
#
# WHAT THIS MAP'S GATE DOES AND DOES NOT PROVE (C43). The membership
# check below compares trigger NAMES ONLY — it never reads a body and
# never compares the SQLite `WHEN` clause against the plpgsql `IF`. So
# it proves the port EXISTS, not that it MEANS the same thing; a body
# mutated to a divergent predicate used to leave --check printing ok.
# `TRIGGER_VERIFICATION` (below) is the compensating control, and it is
# deliberately NOT a plpgsql parser:
#
#   * `verified_by` names the test that pins the predicate this port must
#     match. Generation FAILS when that file does not exist, so a port
#     cannot be added without naming its evidence.
#   * `body_sha256` pins the port body. Any edit to a body without
#     re-recording its digest fails generation, which turns a silent
#     divergence into an explicit, reviewable act.
#
# Neither field is a semantic proof, and this comment is the honest
# statement of that: the digest is a change detector (it forces
# re-acknowledgement, and it can be re-pinned), and `verified_by` is only
# as strong as the named test. For the C42 port
# (stock_summary_qty_nonnegative_*) the named test EXECUTES the plpgsql
# against real PostgreSQL. For the six older ports the named test pins
# the SQLITE trigger's behaviour — a compensating control, NOT PG
# execution; that gap is real and is recorded here rather than implied
# away by a green gate.
TRIGGER_MAP: dict[str, str] = {
    # Retention carve-out (migration 20260920, todo-global-saas-2.md P1):
    # the sweep deletes expired rows through the same
    # settings-key marker (`audit.retention_sweep_active`) the SQLite
    # trigger checks; the sweep holds the marker only inside its own
    # transaction. Mirror of the SQLite WHEN clause.
    "audit_log_immutable_delete": """\
CREATE OR REPLACE FUNCTION audit_log_immutable_delete_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM settings WHERE key = 'audit.retention_sweep_active'
    ) THEN
        RAISE EXCEPTION 'audit_log entries are immutable: DELETE not allowed';
    END IF;
    -- RETURN OLD, NOT NULL (C44). A row-level BEFORE DELETE trigger that
    -- returns NULL CANCELS the delete. The SQLite original is a WHEN-clause
    -- trigger, and a false WHEN means the body never runs and the DELETE
    -- PROCEEDS -- so NULL here made the retention sweep delete nothing while
    -- reporting success: a compliance failure that raises no error anywhere.
    -- Caught only by executing the port against real PostgreSQL.
    RETURN OLD;
END;
$$;

CREATE OR REPLACE TRIGGER audit_log_immutable_delete
    BEFORE DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_immutable_delete_fn();""",
    "audit_log_immutable_update": """\
CREATE OR REPLACE FUNCTION audit_log_immutable_update_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log entries are immutable: UPDATE not allowed';
END;
$$;

CREATE OR REPLACE TRIGGER audit_log_immutable_update
    BEFORE UPDATE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_immutable_update_fn();""",
    # loyalty_tiers validation (SQLite GLOB → Postgres regex). The
    # multiplier arm reads earn_multiplier_millionths — LOYALTY-01
    # replaced the REAL column with fixed-point integer millionths.
    "loyalty_tiers_validate_insert": """\
CREATE OR REPLACE FUNCTION loyalty_tiers_validate_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF trim(NEW.name) = ''
       OR NEW.min_points < 0
       OR NEW.points_per_unit <= 0
       OR NEW.earn_multiplier_millionths <= 0
       OR length(NEW.colour) <> 7
       OR substr(NEW.colour, 1, 1) <> '#'
       OR NEW.colour !~ '^#[0-9A-Fa-f]{6}$'
    THEN
        RAISE EXCEPTION 'invalid loyalty tier configuration';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER loyalty_tiers_validate_insert
    BEFORE INSERT ON loyalty_tiers
    FOR EACH ROW EXECUTE FUNCTION loyalty_tiers_validate_fn();""",
    "loyalty_tiers_validate_update": """\
CREATE OR REPLACE TRIGGER loyalty_tiers_validate_update
    BEFORE UPDATE OF name, min_points, points_per_unit, earn_multiplier_millionths, colour
    ON loyalty_tiers
    FOR EACH ROW EXECUTE FUNCTION loyalty_tiers_validate_fn();""",
    # ADR #47 slice 1: scope_id must be NULL exactly when scope_type is
    # 'organization' (the org-wide row has no single resource). SQLite
    # enforces this with WHEN-clause RAISE triggers; the plpgsql ports are
    # the same predicate as a CHECK-style guard.
    "trg_assignments_scope_id_pair": """\
CREATE OR REPLACE FUNCTION assignments_scope_id_pair_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.scope_type = 'organization') != (NEW.scope_id IS NULL) THEN
        RAISE EXCEPTION 'assignments: scope_id must be NULL exactly when scope_type is organization';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_assignments_scope_id_pair
    AFTER INSERT ON assignments
    FOR EACH ROW EXECUTE FUNCTION assignments_scope_id_pair_fn();""",
    "trg_assignments_scope_id_pair_update": """\
CREATE OR REPLACE TRIGGER trg_assignments_scope_id_pair_update
    AFTER UPDATE OF scope_type, scope_id ON assignments
    FOR EACH ROW EXECUTE FUNCTION assignments_scope_id_pair_fn();""",
    # C10b / owner decision D11: the CONDITIONAL negative-stock backstop on
    # `stock_summary`, ported from
    # `20261012_stock_summary_qty_nonnegative.sql`. The predicate is identical:
    # refuse a negative qty only when the location IS bound and none of its
    # bindings opts into `allow_negative_stock`. The `EXISTS` guard is what
    # keeps an UNBOUND location writable, which the SQLite side needs too
    # (`deactivate_inventory_location_with_negative_stock_errors` seeds a
    # negative at a location with no binding). Postgres shares one function
    # between both arms, exactly as the SQLite file needs two triggers: an
    # INSERT arm and an UPDATE arm, because the `INSERT ... ON CONFLICT DO
    # UPDATE` shape both writers use fires only the latter once the row exists.
    "stock_summary_qty_nonnegative_insert": """\
CREATE OR REPLACE FUNCTION stock_summary_qty_nonnegative_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.qty < 0
       AND EXISTS (
           SELECT 1 FROM workspace_inventory_locations w
            WHERE w.location_id = NEW.location_id
       )
       AND NOT EXISTS (
           SELECT 1 FROM workspace_inventory_locations w
            WHERE w.location_id = NEW.location_id
              AND w.allow_negative_stock = 1
       )
    THEN
        RAISE EXCEPTION 'negative stock requires allow_negative_stock on the location binding';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER stock_summary_qty_nonnegative_insert
    BEFORE INSERT ON stock_summary
    FOR EACH ROW EXECUTE FUNCTION stock_summary_qty_nonnegative_fn();""",
    "stock_summary_qty_nonnegative_update": """\
CREATE OR REPLACE TRIGGER stock_summary_qty_nonnegative_update
    BEFORE UPDATE ON stock_summary
    FOR EACH ROW EXECUTE FUNCTION stock_summary_qty_nonnegative_fn();""",
}

# Compensating control for the NAME-ONLY membership check above (C43).
#
# `verified_by` — the test that pins the predicate this port must match. The
#   path is resolved from the repo root and MUST exist, so a port cannot be
#   added without naming its evidence.
# `body_sha256` — sha256 of the port body, newline-normalized. Any edit to a
#   body without re-recording its digest fails generation.
#
# AS OF C44, ALL SEVEN ENTRIES NAME A TEST THAT EXECUTES THE PORT against a
# real throwaway PostgreSQL database:
#   * stock_summary_qty_nonnegative_* -> apps/cloud-server/tests/pg_stock_guard.rs
#     (C42: all three predicate cases).
#   * the other six -> apps/cloud-server/tests/pg_trigger_ports.rs (C44: both
#     directions where conditional).
# C44 was worth doing rather than declaring: executing the six found a real
# divergence in audit_log_immutable_delete, whose port returned NULL from a
# BEFORE DELETE trigger — which CANCELS the delete — while the SQLite
# WHEN-clause original lets it through when the sweep marker is present. The
# retention sweep therefore deleted nothing and reported success. The body
# digest could not have caught it: the body was wrong from the day it was
# written, and a digest only detects CHANGE.
#
# The residual limit stands: `verified_by` is only as strong as the named
# test, and no field here compares plpgsql semantics to SQL. A NEW port is
# covered the moment it names an executing test; a body that is wrong AND
# whose test does not actually exercise the predicate still passes.
TRIGGER_VERIFICATION: dict[str, dict[str, str]] = {
    "audit_log_immutable_delete": {
        "verified_by": "apps/cloud-server/tests/pg_trigger_ports.rs",
        "note": "EXECUTES this plpgsql against real PostgreSQL (C44); both directions (refused without the sweep marker, the row actually DELETED with it)",
        "body_sha256": "63cbde37094ca88e69b88112e62766d6196e1610d69c8d7658899c2645764029",
    },
    "audit_log_immutable_update": {
        "verified_by": "apps/cloud-server/tests/pg_trigger_ports.rs",
        "note": "EXECUTES this plpgsql against real PostgreSQL (C44); unconditional refusal, incl. under the sweep marker",
        "body_sha256": "889d995af65ea2656ad2a7713f5abaa081d980445c467b7eb469cc5822976757",
    },
    "loyalty_tiers_validate_insert": {
        "verified_by": "apps/cloud-server/tests/pg_trigger_ports.rs",
        "note": "EXECUTES this plpgsql against real PostgreSQL (C44); valid accepted, six invalid shapes refused",
        "body_sha256": "cbe5d469ef17abe21b3d127e0c334320b4acc2dad45f6e3f6cc92df67313251d",
    },
    "loyalty_tiers_validate_update": {
        "verified_by": "apps/cloud-server/tests/pg_trigger_ports.rs",
        "note": "EXECUTES this plpgsql against real PostgreSQL (C44); valid update accepted, invalid refused",
        "body_sha256": "590edd3ea39682af1e3ba60ea9ba894bb7dbf66d7420cf83639724fe94ea115f",
    },
    "trg_assignments_scope_id_pair": {
        "verified_by": "apps/cloud-server/tests/pg_trigger_ports.rs",
        "note": "EXECUTES this plpgsql against real PostgreSQL (C44); two valid shapes accepted, two invalid refused",
        "body_sha256": "021fccd42df444737cd25bb99b3fcca42a5191d6da385bd10b92bd4b833ab3a2",
    },
    "trg_assignments_scope_id_pair_update": {
        "verified_by": "apps/cloud-server/tests/pg_trigger_ports.rs",
        "note": "EXECUTES this plpgsql against real PostgreSQL (C44); valid transition accepted, both invalid refused",
        "body_sha256": "5bf43fc06622c13ffde841a33fd94fd6ca62504c573785c892223055459ba822",
    },
    "stock_summary_qty_nonnegative_insert": {
        "verified_by": "apps/cloud-server/tests/pg_stock_guard.rs",
        "note": "EXECUTES this plpgsql against real PostgreSQL (C42), all three predicate cases",
        "body_sha256": "de2dbc9691b7ce8f1116a4dde18804c879f2da2085e3a49bf42caa9414343a2c",
    },
    "stock_summary_qty_nonnegative_update": {
        "verified_by": "apps/cloud-server/tests/pg_stock_guard.rs",
        "note": "EXECUTES this plpgsql against real PostgreSQL (C42), all three predicate cases",
        "body_sha256": "e9026abf057aa52281d38685ed9b10ae80d57370b9e7b671e23b53227b6446e3",
    },
}

# Data statements a SQLite migration performs BEFORE a DDL statement that would
# otherwise fail on the un-repaired rows (C38).
#
# WHY THIS LIST EXISTS. The generator rebuilds the PG schema from the FINAL
# SQLite state: it re-emits tables, indexes, triggers and seeds, and it drops
# every DML statement in the migration chain (measured: the generated file
# contains ZERO UPDATE statements, while seven migrations carry one). That is
# correct for a statement that only converges rows the final schema already
# implies — but WRONG for a migration whose UPDATE exists to make a following
# DDL statement applicable. 20261011_open_shift_uniqueness.sql closes every open
# shift but the newest for a user BEFORE creating idx_shifts_open_per_user, and
# its own header says why the halves must travel together: "the index without
# its reconciliation is exactly the startup-bricking shape this file exists to
# prevent". The PG twin carried the bare index, so a PostgreSQL database holding
# two open shifts for one user failed at init.
#
# WHY NOT TRANSLATE THE DML GENERICALLY. SQLite DML does not port mechanically
# (strftime, GLOB, row-value comparisons all differ), and a half-working
# translation fails in exactly the way this list exists to prevent. An explicit,
# declared, digest-pinned entry keeps the port hand-written and reviewable —
# the same discipline TRIGGER_MAP uses.
#
# SHAPE: (index_name, sql, verified_by, body_sha256).
#   * index_name    — the index this reconciliation must run BEFORE. It must
#                     name an index the generator actually emits, so a stale
#                     entry fails generation instead of emitting a statement
#                     nothing depends on.
#   * sql           — the hand-written Postgres reconciliation.
#   * verified_by   — the test that EXECUTES it against real PostgreSQL.
#                     Generation FAILS when the path does not exist, so a
#                     reconciliation cannot be added without naming its
#                     evidence (the C43/C44 rule).
#   * body_sha256   — pins the statement, so an edit cannot ride along silently.
#
# The SQL is wrapped in a to_regclass guard by render_pre_index_reconciliations,
# so it is a no-op on a fresh database (where the table does not exist yet at
# this point) and effective on one that already holds the offending rows.
PRE_INDEX_RECONCILIATIONS: list[dict[str, str]] = [
    {
        "index_name": "idx_shifts_open_per_user",
        "sql": """\
UPDATE shifts
   SET status = 'closed',
       closed_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
       closing_balance_minor = NULL,
       expected_cash_minor = NULL,
       cash_difference_minor = NULL,
       notes = CASE WHEN notes = ''
                    THEN 'auto-closed: duplicate open shift (COR-27 reconciliation)'
                    ELSE notes || ' | auto-closed: duplicate open shift (COR-27 reconciliation)' END,
       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
 WHERE status = 'open'
   AND EXISTS (
       SELECT 1 FROM shifts newer
        WHERE newer.user_id = shifts.user_id
          AND newer.status = 'open'
          AND (newer.opened_at, newer.id) > (shifts.opened_at, shifts.id)
   );""",
        "verified_by": "apps/cloud-server/tests/pg_init_reconciliation.rs",
        "body_sha256": "d706e0a43cc96278c4d11f5d8e3127d2600c64f18a4ffd0d70ff8a45549c643b",
    },
]

# Seed timestamps younger than this are "now"-derived (the migration run
# just stamped them) and re-emitted as the PG now-expression; older
# literals are fixed seed data and survive verbatim. 1 hour is orders of
# magnitude above any plausible build-vs-check gap while staying far
# below real seed dates.
NOW_FRESHNESS_SECONDS = 3600
ISO_RE = re.compile(r"^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}")


def registry_ids() -> list[str]:
    """Migration ids in canonical registry order (the Rust array order)."""
    text = REGISTRY_RS.read_text(encoding="utf-8")
    ids = re.findall(r'id:\s*"([^"]+\.sql)"', text)
    if not ids:
        raise SystemExit("error: could not parse any migration ids from migrations.rs")
    return ids


def build_db(ids: list[str]) -> sqlite3.Connection:
    db = sqlite3.connect(":memory:")
    for i in ids:
        sql = (MIG_DIR / i).read_text(encoding="utf-8")
        db.executescript(sql)
        db.commit()
    return db


# Schema-evolution statements the snapshot cannot express. `CREATE TABLE IF
# NOT EXISTS` is inert for a table that already exists, so a RENAME or a DROP
# that a SQLite migration performed is simply invisible to Postgres: the
# legacy table/column stays, and the snapshot's version is created alongside
# it. Replaying the operations is the only faithful port — and replaying a
# RENAME (rather than re-creating the new name) is what preserves the rows.
RENAME_COLUMN_RE = re.compile(
    r"ALTER\s+TABLE\s+\"?(\w+)\"?\s+RENAME\s+COLUMN\s+\"?(\w+)\"?\s+TO\s+\"?(\w+)\"?",
    re.I,
)
RENAME_TABLE_RE = re.compile(
    r"ALTER\s+TABLE\s+\"?(\w+)\"?\s+RENAME\s+TO\s+\"?(\w+)\"?", re.I
)


def schema_evolution_ops() -> tuple[
    list[tuple[str, str, str]], list[tuple[str, str, str, str]]
]:
    """``(table renames, column renames)`` parsed from the migration chain.

    Derived rather than listed so the port cannot drift from the source of
    truth. Order is registry order, which is the order the SQLite side
    applies them in. Each tuple carries the migration id it came from, so
    the emitted SQL names its own provenance.

    Table rebuilds (``x_new`` RENAME TO ``x``) are parsed too but are inert:
    the replay is guarded on the source existing and the target not, and
    ``x_new`` never exists in a database that ran the chain normally.
    """
    table_renames: list[tuple[str, str, str]] = []
    column_renames: list[tuple[str, str, str, str]] = []
    for mid in registry_ids():
        sql = (MIG_DIR / mid).read_text(encoding="utf-8")
        column_renames.extend(
            (m.group(1), m.group(2), m.group(3), mid)
            for m in RENAME_COLUMN_RE.finditer(sql)
        )
        table_renames.extend(
            (m.group(1), m.group(2), mid) for m in RENAME_TABLE_RE.finditer(sql)
        )
    return table_renames, column_renames


def convert_table(stmt: str) -> str:
    """Apply the type/default mapping to a dumped CREATE TABLE statement."""
    s = stmt.replace("strftime('%Y-%m-%dT%H:%M:%fZ', 'now')", TS_PG)
    s = s.replace("datetime('now')", DT_PG)
    s = s.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    s = re.sub(r"\bINTEGER\b", "BIGINT", s)
    s = re.sub(r"\bREAL\b", "DOUBLE PRECISION", s)
    # Drop the SQLite STRICT table option (no Postgres equivalent).
    s = re.sub(r"\s+STRICT(?=\s*;?\s*$)", "", s)
    # sqlite_master stores the statement without IF NOT EXISTS even when
    # the migration used it; re-add for idempotent re-apply.
    s = re.sub(r"^CREATE TABLE (?!IF NOT EXISTS)", "CREATE TABLE IF NOT EXISTS ", s)
    return s.rstrip().rstrip(";") + ";"


def topo_sort(tables: list[tuple[str, set[str], str]]) -> list[tuple[str, set[str], str]]:
    """Kahn-sort tables so a referenced table is always created first."""
    by_name = {name: (name, refs, text) for name, refs, text in tables}
    names = [name for name, _, _ in tables]
    name_set = set(names)
    indegree = {n: 0 for n in names}
    adj: dict[str, list[str]] = defaultdict(list)
    for name, refs, _ in tables:
        for ref in refs:
            if ref in name_set and ref != name:
                adj[ref].append(name)
                indegree[name] += 1
    queue = deque(n for n in names if indegree[n] == 0)
    ordered: list[str] = []
    while queue:
        n = queue.popleft()
        ordered.append(n)
        for m in adj[n]:
            indegree[m] -= 1
            if indegree[m] == 0:
                queue.append(m)
    # A cycle should never happen; fall back to original order if it does.
    for n in names:
        if n not in ordered:
            ordered.append(n)
    return [by_name[n] for n in ordered]


def _quote(value: object) -> str:
    """SQL literal for a seed value, with the now-derived timestamp rule."""
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return repr(value) if isinstance(value, float) else str(value)
    if isinstance(value, bytes):
        raise SystemExit(f"error: BLOB seed data is not supported: {value[:16]!r}…")
    s = str(value)
    if ISO_RE.match(s):
        try:
            dt = datetime.fromisoformat(s.replace("Z", "+00:00").replace(" ", "T"))
            age = abs((dt - datetime.now(timezone.utc)).total_seconds())
            if age < NOW_FRESHNESS_SECONDS:
                return TS_PG
        except ValueError:
            pass
    return "'" + s.replace("'", "''") + "'"


def dump_seeds(db: sqlite3.Connection, ordered_tables: list[str]) -> list[str]:
    """One idempotent INSERT per non-empty table, in FK-topological order
    (seed tables reference each other: workspace_instances → workspace_types)."""
    out: list[str] = []
    for t in ordered_tables:
        cols = [c[1] for c in db.execute(f'PRAGMA table_info("{t}")')]
        rows = db.execute(f'SELECT * FROM "{t}" ORDER BY rowid').fetchall()
        if not rows:
            continue
        col_list = ", ".join(cols)
        values = ",\n    ".join(
            "(" + ", ".join(_quote(v) for v in row) + ")" for row in rows
        )
        out.append(
            f"INSERT INTO {t} ({col_list}) VALUES\n    {values}\n"
            "ON CONFLICT DO NOTHING;"
        )
    return out


def dump_rls(db: sqlite3.Connection) -> str:
    """RLS appendix over the CURATED RLS_TABLES list.

    Enabling RLS on a table is a policy decision, not a schema fact: the
    write path must set `tenant_id` on every INSERT or the policy's
    WITH CHECK rejects it (sale_lines was the cautionary example — it
    sat uncovered until its pg.rs write path started stamping the
    column). So the list is curated,
    and the generator fails closed on staleness: every entry must exist
    in the final schema AND carry a tenant_id column. Tables that have
    tenant_id but are not yet covered are emitted as a visible comment
    block — the to-do list, never silently enabled.
    """
    final = {
        r[0]
        for r in db.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%'"
        )
    }
    tenant_tables = {
        t
        for t in final
        if any(
            c[1] == "tenant_id"
            for c in db.execute(f'PRAGMA table_info("{t}")')
        )
    }
    stale = [t for t in RLS_TABLES if t not in tenant_tables]
    if stale:
        raise SystemExit(
            "error: RLS_TABLES entries are no longer tenant tables "
            f"(dropped or lost tenant_id): {', '.join(stale)}"
        )
    check_rls_coverage(tenant_tables, set(RLS_TABLES), RLS_EXEMPT)
    uncovered = sorted(tenant_tables - set(RLS_TABLES))
    quoted = ",\n                            ".join(
        ", ".join(f"'{t}'" for t in chunk) for chunk in _chunks(sorted(RLS_TABLES), 6)
    )
    gap_comment = ""
    if uncovered:
        gap_comment = (
            "-- tenant_id tables NOT yet under RLS — documented exemptions\n"
            "-- (RLS_EXEMPT in scripts/generate-pg-migration.py; the reason\n"
            "-- travels with the entry, and an undocumented table fails the\n"
            "-- generator):\n"
            + "".join(f"--   {t} — {RLS_EXEMPT[t]}\n" for t in uncovered)
            + "--\n"
        )
    return gap_comment + RLS_TEMPLATE.replace("__TABLES__", quoted)


def check_rls_coverage(
    tenant_tables: set[str], covered: set[str], exempt: dict[str, str]
) -> None:
    """Fail closed in both directions (the generalized RLS coverage gate).

    Every tenant_id-bearing table must be either RLS-covered or
    documented-exempt with a reason (``exempt`` maps table → reason); a
    table that is neither fails generation, so a migration can never
    silently add tenant_id coverage debt. The mirror direction fails
    too: an exemption for a table that is now covered or lost the
    column/table is stale and must be deleted.
    """
    undocumented = sorted(tenant_tables - covered - set(exempt))
    if undocumented:
        raise SystemExit(
            "error: tenant_id tables that are neither RLS-covered nor "
            "documented-exempt (add to RLS_TABLES once every write path "
            "stamps tenant_id, or record the reason in RLS_EXEMPT): "
            + ", ".join(undocumented)
        )
    stale = sorted(set(exempt) - (tenant_tables - covered))
    if stale:
        raise SystemExit(
            "error: stale RLS_EXEMPT entries (table is now covered or "
            "lost tenant_id — delete the exemption): " + ", ".join(stale)
        )


def check_trigger_verification(
    ports: dict[str, str],
    verification: dict[str, dict[str, str]],
    root: Path,
) -> None:
    """Fail closed when a trigger port carries no live verification.

    The membership check in render() compares trigger NAMES only, so it
    proves a port EXISTS and never that it MEANS the same thing. This gate is
    the compensating control, and it is deliberately not a plpgsql parser:

    1. every port must declare verified_by - a test path that EXISTS - so a
       port cannot be added without naming the evidence that pins it;
    2. every port must pin body_sha256 matching its current body, so an edit
       to a body cannot ride along silently: it fails generation until the
       author re-records the digest, which makes the change explicit and
       reviewable rather than invisible.

    Neither is a semantic proof. The digest is a change detector (and can be
    re-pinned); verified_by is only as strong as the named test. Both are
    stated in the TRIGGER_VERIFICATION comment rather than implied away.
    """
    undeclared = sorted(set(ports) - set(verification))
    if undeclared:
        raise SystemExit(
            "error: trigger ports with no verification entry (declare "
            "verified_by - the test that pins the predicate - and "
            "body_sha256 in TRIGGER_VERIFICATION): " + ", ".join(undeclared)
        )
    stale = sorted(set(verification) - set(ports))
    if stale:
        raise SystemExit(
            "error: stale TRIGGER_VERIFICATION entries (no such port - "
            "delete the entry): " + ", ".join(stale)
        )

    problems: list[str] = []
    for name in sorted(ports):
        entry = verification[name]
        test_path = entry.get("verified_by", "")
        if not test_path:
            problems.append(f"{name}: no verified_by")
        elif not (root / test_path).is_file():
            problems.append(
                f"{name}: verified_by names a missing test: {test_path}")
        declared = entry.get("body_sha256", "")
        actual = hashlib.sha256(
            ports[name].replace("\r\n", "\n").encode("utf-8")
        ).hexdigest()
        if declared != actual:
            problems.append(
                f"{name}: body changed (declared {declared[:12]}, actual "
                f"{actual[:12]}) - re-record body_sha256 in TRIGGER_VERIFICATION "
                "after confirming the port still matches the SQLite predicate"
            )
    if problems:
        raise SystemExit(
            "error: trigger verification failed (the membership check proves "
            "presence only, never semantics):\n  - " + "\n  - ".join(problems)
        )


def _self_test_trigger_gate() -> None:
    """Exercise the verification gate fail directions on synthetic sets."""
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "a_test.rs").write_text("// stand-in", encoding="utf-8")
        body = "CREATE OR REPLACE TRIGGER t ..."
        digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
        good = {"t": {"verified_by": "a_test.rs", "body_sha256": digest}}
        # The passing direction must actually pass.
        check_trigger_verification({"t": body}, good, root)

        failures = [
            ({"t": body}, {}, "port with no verification entry"),
            ({"t": body, "u": body}, good, "port missing from verification"),
            ({"t": body}, {"t": good["t"], "ghost": good["t"]}, "verification entry with no port"),
            ({"t": body}, {"t": {"verified_by": "", "body_sha256": digest}}, "blank verified_by"),
            ({"t": body}, {"t": {"verified_by": "nope.rs", "body_sha256": digest}}, "verified_by names a missing test"),
            ({"t": body}, {"t": {"verified_by": "a_test.rs", "body_sha256": "0" * 64}}, "body digest mismatch (the C43 mutation case)"),
        ]
        for ports, verification, case in failures:
            try:
                check_trigger_verification(ports, verification, root)
            except SystemExit:
                continue
            raise SystemExit(
                f"error: trigger verification gate self-test: {case} did not fail")
    print("ok: trigger verification gate self-test (fail-closed in both directions)")


def _self_test_pre_index_gate() -> None:
    """Exercise the pre-index reconciliation gate fail directions."""
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "a_test.rs").write_text("// stand-in", encoding="utf-8")
        sql = "UPDATE shifts SET status = 'closed';"
        digest = hashlib.sha256(sql.encode("utf-8")).hexdigest()
        good = [{"index_name": "idx_x", "sql": sql, "verified_by": "a_test.rs", "body_sha256": digest}]
        # The passing direction must actually pass, and an empty list is legal.
        check_pre_index_reconciliations(good, {"idx_x"}, root)
        check_pre_index_reconciliations([], set(), root)

        failures = [
            ([{"index_name": "", "sql": sql, "verified_by": "a_test.rs", "body_sha256": digest}], {"idx_x"}, "entry with no index_name"),
            ([{**good[0], "index_name": "idx_ghost"}], {"idx_x"}, "stale entry naming an unemitted index"),
            ([{**good[0], "verified_by": ""}], {"idx_x"}, "blank verified_by"),
            ([{**good[0], "verified_by": "nope.rs"}], {"idx_x"}, "verified_by names a missing test"),
            ([{**good[0], "body_sha256": "0" * 64}], {"idx_x"}, "reconciliation digest mismatch"),
            ([good[0], good[0]], {"idx_x"}, "duplicate entry for one index"),
        ]
        for entries, emitted, case in failures:
            try:
                check_pre_index_reconciliations(entries, emitted, root)
            except SystemExit:
                continue
            raise SystemExit(
                f"error: pre-index reconciliation gate self-test: {case} did not fail"
            )
    print("ok: pre-index reconciliation gate self-test (fail-closed in both directions)")


def _self_test_rls_gate() -> None:
    """Exercise the coverage gate's fail directions on synthetic sets."""
    check_rls_coverage({"a", "b"}, {"a"}, {"b": "pending write path"})
    failures = [
        ({"a", "b", "c"}, {"a"}, {"b": "x"}, "undocumented uncovered table"),
        ({"a", "b"}, {"a", "b"}, {"b": "x"}, "exempt table is covered"),
        ({"a"}, {"a"}, {"ghost": "x"}, "exempt table does not exist"),
    ]
    for tenant_tables, covered, exempt, case in failures:
        try:
            check_rls_coverage(tenant_tables, covered, exempt)
        except SystemExit:
            continue
        raise SystemExit(
            f"error: RLS coverage gate self-test: {case} did not fail"
        )
    print("ok: RLS coverage gate self-test (fail-closed in both directions)")


# Curated RLS coverage — carried over from the hand-ported init.pg.sql
# (product_activity's tenant_id was PG-only hand-port fiction until the
# 20260831 rebuild migration added the real column on the SQLite side).
# Add a table here only after its REST/sync write path demonstrably sets
# tenant_id; the generator validates the entries.
RLS_TABLES = [
    "bundle_items",
    "edc_terminals",
    "entity_index_cursors",
    "entity_index_tombstones",
    "memo_locations",
    "memo_recipients",
    "memos",
    "midtrans_transactions",
    "offline_queue",
    "product_activity",
    "product_bundles",
    "product_taxes",
    "product_variants",
    "products",
    "receipt_number_counters",
    "refunds",
    "sale_idempotency",
    "sale_lines",
    "sales",
    "sent_reports",
    "stripe_customers",
    "sync_conflicts",
    "sync_entity_vectors",
    "sync_terminals",
    "tax_rates",
    "tenant_plans",
    "tenant_subscription",
    "users",
    "locations",
]

# Deliberate non-coverage: every tenant_id-bearing table that is NOT in
# RLS_TABLES must appear here with the reason it cannot be enabled yet,
# or the generator fails (the Round-37 gate: a table may neither silently
# gain tenant_id nor silently become covered — check_rls_coverage fails
# closed in both directions). Remove an entry the moment the table's
# write path stamps tenant_id and it joins RLS_TABLES.
RLS_EXEMPT = {
    "receipt_formats": (
        "regional receipt-format axis; desktop-local write paths only "
        "(Store CRUD via the scoped commands) — tenant_id stamped "
        "schema-side from birth, cover when its PG write path lands; "
        "parent legal_entities is itself exempt pending the cloud-sync "
        "decision"
    ),
    "local_payment_methods": (
        "regional slice 6; desktop-local write paths only (Store CRUD via "
        "the scoped commands) — tenant_id stamped schema-side from birth, "
        "cover when its PG write path lands; parent legal_entities is "
        "itself exempt pending the cloud-sync decision"
    ),
    "document_number_sequences": (
        "regional slice 5; desktop-local write paths only (Store CRUD + "
        "the checkout claim) — tenant_id stamped schema-side from birth, "
        "cover when its PG write path lands; parent legal_entities is "
        "itself exempt pending the cloud-sync decision, and covering a "
        "child while the parent is uncovered would be incoherent"
    ),
    "fiscal_schemes": (
        "regional slice 5; desktop-local write paths only (Store CRUD) — "
        "tenant_id stamped schema-side from birth, cover when its PG "
        "write path lands; parent legal_entities is itself exempt "
        "pending the cloud-sync decision"
    ),
    "image_refs": (
        "no PG write path audited; desktop-local image references — "
        "cover when its cloud sync path lands"
    ),
    "media_assets": (
        "no writer anywhere in the repo — no INSERT/UPDATE exists outside "
        "the CREATE TABLE in 20260824_media_edc.sql; db/media.rs is a "
        "fail-fast stub (create_media_asset returns PLANNED) and the image "
        "GC loop only DELETEs. RLS is an isolation guarantee only where the "
        "write path stamps tenant_id, so there is nothing for a policy to "
        "gate yet — move back to RLS_TABLES when the media pipeline writes it"
    ),
    "media_thumbnails": (
        "no writer anywhere in the repo — no INSERT/UPDATE exists outside "
        "the CREATE TABLE in 20260824_media_edc.sql; db/media.rs is a "
        "fail-fast stub and the image GC loop only DELETEs. Nothing to gate "
        "until the media pipeline persists thumbnails"
    ),
    "legal_entities": (
        "§G slice pending the cloud-sync decision; local CRUD paths "
        "exist but no PG write path is audited yet"
    ),
    "memo_revisions": (
        "append-only revision history with no PG write path at all "
        "(pg.rs never touches it) — nothing for a policy to gate"
    ),
    "payment_gateways": (
        "no writer anywhere in the repo — no INSERT/UPDATE exists outside "
        "the CREATE TABLE in 20260825_payment_infra.sql; db/payment_gateways.rs "
        "is a fail-fast stub (upsert_gateway returns PLANNED) and the copier's "
        "DEFAULT_TABLES excludes it. Nothing to gate until gateway config CRUD "
        "lands"
    ),
    "payment_settlements": (
        "no writer anywhere in the repo — no INSERT/UPDATE exists outside "
        "the CREATE TABLE in 20260825_payment_infra.sql; "
        "db/payment_settlements.rs is a fail-fast stub (record_settlement "
        "returns PLANNED) and the copier's DEFAULT_TABLES excludes it. Nothing "
        "to gate until the reconciliation job writes it"
    ),
    "payable_payments": (
        "no PG write path yet; desktop-local AP settlement history — "
        "cover when payables cloud sync lands"
    ),
    "payables": (
        "no PG write path yet; desktop-local AP ledger (Hutang) — "
        "cover when payables cloud sync lands"
    ),
    "snapshot_versions": (
        "no PG write path audited; cover when snapshot sync reaches PG"
    ),
    "terminals": (
        "tenant_id added schema-side (56653839) ahead of multi-tenant "
        "writes; cover when create_terminal-class PG writes arrive"
    ),
    "topology_revisions": (
        "ADR #46 desktop-side table; no PG write path yet"
    ),
    "over_quota_markers": (
        "tenant_id added schema-side ahead of multi-tenant writes; "
        "no PG write path audited yet -- cover when cloud sync lands"
    ),
    "webhook_endpoints": (
        "no PG write path audited; cover when the admin surface "
        "writes it on PG"
    ),
    "user_location_access": (
        "no writer anywhere in the repo — no production INSERT/UPDATE exists; "
        "the only INSERTs are test fixtures (db/locations_tests.rs, "
        "db/workspaces_tests.rs) and no dynamically built statement names it. "
        "Every production reference is a read: the multi-store check in "
        "db/workspaces_instances.rs only SELECTs, and the REST surface grants "
        "but never writes. RLS is an isolation guarantee only where the write "
        "path stamps tenant_id, so there is nothing for a policy to gate yet — "
        "move back to RLS_TABLES when user-location assignment CRUD lands"
    ),
    "provisioning": (
        "ADR #56 first-run record; written only by the desktop/tablet "
        "provision_device transaction against the LOCAL store DB, and never "
        "synced to PG. It records which server holds this tenant's data, so "
        "replicating it into the shared cloud schema would put one install's "
        "routing fact in every other tenant's reach for no read that exists. "
        "Cover if provisioning ever moves cloud-side"
    ),
}


def _chunks(items: list[str], size: int):
    for i in range(0, len(items), size):
        yield items[i : i + size]


RLS_TEMPLATE = """-- ── Row-Level Security: tenant isolation (PG-only) ─────────────────────
-- Curated coverage list (RLS_TABLES in scripts/generate-pg-migration.py);
-- the generator fails if an entry loses its tenant_id column or table.
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[__TABLES__]
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies
            WHERE schemaname = 'public' AND tablename = t AND policyname = 'tenant_isolation'
        ) THEN
            EXECUTE format(
                'CREATE POLICY tenant_isolation ON %I
                 USING (tenant_id = current_setting(''oz.tenant_id'', true))
                 WITH CHECK (tenant_id = current_setting(''oz.tenant_id'', true))',
                t
            );
        END IF;
    END LOOP;
END $$;
"""


def _sql_literal(value: str) -> str:
    """Single-quoted SQL literal with internal quotes doubled."""
    return "'" + value.replace("'", "''") + "'"


def _pg_type(sqlite_type: str) -> str:
    """Type mapping for a PRAGMA-reported type (same rules as convert_table)."""
    t = (sqlite_type or "").strip() or "TEXT"
    t = re.sub(r"\bINTEGER\b", "BIGINT", t)
    t = re.sub(r"\bREAL\b", "DOUBLE PRECISION", t)
    return t


def _pg_default(sqlite_default: str) -> str:
    """Default mapping for a PRAGMA-reported default (same rules as convert_table)."""
    s = sqlite_default.replace("strftime('%Y-%m-%dT%H:%M:%fZ', 'now')", TS_PG)
    return s.replace("datetime('now')", DT_PG)


def pg_column_specs(
    db: sqlite3.Connection, ordered: list[str]
) -> list[tuple[str, str, str, str | None, bool]]:
    """``(table, column, pg_type, pg_default_or_None, not_null)`` per column.

    Read from ``PRAGMA table_info`` rather than by parsing the rendered DDL.
    SQLite keeps ``table_info`` current across ADD/DROP COLUMN, so it reports
    the same final state the CREATE TABLE dump is taken from — and it needs no
    fragile parsing of statements whose formatting the migrations control.
    """
    specs: list[tuple[str, str, str, str | None, bool]] = []
    for table in ordered:
        pragma = 'PRAGMA table_info("%s")' % table.replace('"', '""')
        for _cid, name, sqlite_type, notnull, dflt, pk in db.execute(pragma):
            specs.append(
                (
                    table,
                    name,
                    _pg_type(sqlite_type),
                    None if dflt is None else _pg_default(dflt),
                    bool(notnull) or bool(pk),
                )
            )
    return specs


RECONCILE_TEMPLATE = """\
-- ── Column reconciliation for pre-existing databases ───────────────────
-- CREATE TABLE IF NOT EXISTS is idempotent for TABLES but inert for
-- COLUMNS: a table created by an earlier revision of this script is
-- skipped whole, so every column added to it since is silently absent.
-- That is not theoretical — on 2026-09-18 the deployed cloud-server
-- crash-looped for five days with
--
--     ERROR: column "legal_entity_id" does not exist
--     LINE 4: AND legal_entity_id IS NOT NULL
--
-- because `tax_rates` predated the 2026-09-08 scoping migration and the
-- 2026-09-09 partial index that reads the new column. Reproduced against
-- a real Postgres 16 from the schema of the last deployed sha.
--
-- The block below converges ANY earlier database onto the column set
-- this script declares. It is generated from the same final SQLite state
-- as the CREATE TABLE statements, so it cannot rot: a column added to an
-- existing table in any future migration is picked up automatically.
--
-- Two deliberate limits:
--   * It runs BEFORE the DDL, so every action is guarded on the table
--     already existing. On a fresh database it is a no-op and the
--     CREATE TABLE statements below create everything.
--   * It restores COLUMNS and NOT NULL, never FOREIGN KEY / PRIMARY KEY /
--     UNIQUE / CHECK. Those can be unsatisfiable on legacy rows, and a
--     failure here aborts the whole migration (batch_execute is one
--     implicit transaction) — i.e. it would re-create the very outage
--     this block exists to end. A migrated database therefore differs
--     from a fresh one by the absence of the foreign keys named in the
--     scoping migrations; that gap is tracked, not hidden.
--
-- A NOT NULL column is added NULLABLE and promoted only when no row is
-- NULL, so a legacy row can never be invented into compliance. When the
-- promotion is refused the run raises a WARNING naming the table, the
-- column and the NULL count.
DO $oz_reconcile$
DECLARE
    r RECORD;
    n_null BIGINT;
BEGIN
    FOR r IN
        SELECT * FROM (VALUES
__ROWS__
        ) AS v(tbl, col, typ, dflt, nn)
    LOOP
        IF EXISTS (SELECT 1 FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_name = r.tbl)
           AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = r.tbl
                      AND column_name = r.col)
        THEN
            EXECUTE format('ALTER TABLE public.%I ADD COLUMN %I %s%s',
                           r.tbl, r.col, r.typ,
                           CASE WHEN r.dflt IS NULL THEN ''
                                ELSE ' DEFAULT ' || r.dflt END);
        END IF;

        -- Only ever touched while the catalog still says NULLABLE: on a
        -- converged database this branch is not entered, so no boot pays
        -- for a COUNT(*) over every NOT NULL column.
        IF r.nn
           AND EXISTS (SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = r.tbl
                          AND column_name = r.col AND is_nullable = 'YES')
        THEN
            EXECUTE format('SELECT count(*) FROM public.%I WHERE %I IS NULL',
                           r.tbl, r.col) INTO n_null;
            IF n_null = 0 THEN
                EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I SET NOT NULL',
                               r.tbl, r.col);
            ELSE
                RAISE WARNING 'oz schema reconcile: %.% stays NULLABLE (% row(s) are NULL); a fresh database declares it NOT NULL',
                    r.tbl, r.col, n_null;
            END IF;
        END IF;
    END LOOP;
END
$oz_reconcile$;"""


EVOLVE_TABLE_TEMPLATE = """\
    -- __SRC__ -> __DST__   (__MID__)
    IF EXISTS (SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = __SRC__)
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = __DST__)
    THEN
        EXECUTE format('ALTER TABLE public.%I RENAME TO %I', __SRC__, __DST__);
    END IF;"""

EVOLVE_COLUMN_TEMPLATE = """\
    -- __TBL__.__FROM__ -> __TO__   (__MID__)
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = __TBL__
                  AND column_name = __FROM__)
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = __TBL__
                  AND column_name = __TO__)
    THEN
        EXECUTE format('ALTER TABLE public.%I RENAME COLUMN %I TO %I',
                       __TBL__, __FROM__, __TO__);
    END IF;"""


def render_evolution_ops(
    table_renames: list[tuple[str, str, str]],
    column_renames: list[tuple[str, str, str, str]],
) -> str:
    """Guarded replay of RENAMEs the snapshot cannot express.

    Table renames are emitted before column renames because a column rename
    can target a table that was itself just renamed (20260906 renames
    ``user_store_access`` and then one of its columns).

    This must run BEFORE the column reconciliation: replaying a rename
    preserves the rows, whereas letting the reconciliation "add" the new
    column instead would leave the legacy NOT NULL column behind — which is
    what made the 2026-09-18 seed inserts fail with
    ``null value in column "max_stores" ... violates not-null constraint``.
    """
    body: list[str] = []
    for src, dst, mid in table_renames:
        body.append(
            EVOLVE_TABLE_TEMPLATE.replace("__SRC__", _sql_literal(src))
            .replace("__DST__", _sql_literal(dst))
            .replace("__MID__", mid)
        )
    for tbl, frm, to, mid in column_renames:
        body.append(
            EVOLVE_COLUMN_TEMPLATE.replace("__TBL__", _sql_literal(tbl))
            .replace("__FROM__", _sql_literal(frm))
            .replace("__TO__", _sql_literal(to))
            .replace("__MID__", mid)
        )
    return "\n".join(
        [
            "-- ── Schema evolution replayed from the migration chain ──────────────",
            "-- A RENAME or a DROP performed by a SQLite migration is invisible to",
            "-- Postgres: CREATE TABLE IF NOT EXISTS skips the table whole, so the",
            "-- legacy name survives and the snapshot's name is created alongside",
            "-- it. Two consequences, both measured against Postgres 16 on",
            "-- 2026-09-18: the seed inserts died on the legacy NOT NULL columns",
            "-- (``max_stores``, ``workspace_instances.store_id``) that the rename",
            "-- was supposed to have carried away, and `locations` came up empty",
            "-- while the real rows sat in the un-renamed `store_profiles`.",
            "--",
            "-- Each replay is guarded on the source existing and the target not,",
            "-- so it is a no-op on a fresh database and on one already converged.",
            "DO $oz_evolve$",
            "BEGIN",
            "\n\n".join(body),
            "END",
            "$oz_evolve$;",
        ]
    )


def render_reconciliation(
    specs: list[tuple[str, str, str, str | None, bool]],
) -> str:
    """The guarded column-reconciliation DO block (see RECONCILE_TEMPLATE)."""
    rows = ",\n".join(
        "            (%s, %s, %s, %s, %s)"
        % (
            _sql_literal(table),
            _sql_literal(col),
            _sql_literal(typ),
            "NULL::text" if dflt is None else _sql_literal(dflt),
            "true" if notnull else "false",
        )
        for table, col, typ, dflt, notnull in specs
    )
    return RECONCILE_TEMPLATE.replace("__ROWS__", rows)


def check_pre_index_reconciliations(
    entries: list[dict[str, str]],
    emitted_indexes: set[str],
    root: Path,
) -> None:
    """Fail closed when a pre-index reconciliation is undeclared or unverified.

    The generator drops every DML statement in the migration chain, so a
    reconciliation that makes a following DDL statement applicable must be
    declared here explicitly. This gate enforces the declaration the way
    check_trigger_verification enforces the trigger ports: a named test that
    EXISTS (so the reconciliation cannot be added without evidence) and a body
    digest (so an edit cannot ride along silently). It also fails a stale entry
    naming an index the generator does not emit, which would otherwise place a
    statement nothing depends on.
    """
    if not entries:
        return
    problems: list[str] = []
    seen: set[str] = set()
    for entry in entries:
        name = entry.get("index_name", "")
        if not name:
            problems.append("entry with no index_name")
            continue
        if name in seen:
            problems.append(f"{name}: duplicate entry")
        seen.add(name)
        if name not in emitted_indexes:
            problems.append(
                f"{name}: names an index the generator does not emit (stale entry)"
            )
        test_path = entry.get("verified_by", "")
        if not test_path:
            problems.append(f"{name}: no verified_by")
        elif not (root / test_path).is_file():
            problems.append(f"{name}: verified_by names a missing test: {test_path}")
        declared = entry.get("body_sha256", "")
        actual = hashlib.sha256(
            entry.get("sql", "").replace("\r\n", "\n").encode("utf-8")
        ).hexdigest()
        if declared != actual:
            problems.append(
                f"{name}: reconciliation changed (declared {declared[:12]}, actual "
                f"{actual[:12]}) — re-record body_sha256 in "
                "PRE_INDEX_RECONCILIATIONS after confirming it still matches the "
                "SQLite migration"
            )
    if problems:
        raise SystemExit(
            "error: pre-index reconciliation failed (a dropped DML statement that "
            "a DDL statement depends on bricks PG init):\n  - " + "\n  - ".join(problems)
        )


def render_pre_index_reconciliations(index_tables: dict[str, str]) -> str:
    """Emit each declared reconciliation, guarded, immediately before its index.

    The guard is to_regclass: on a fresh database the table does not exist at
    this point in the script (the CREATE TABLE comes later, because these
    statements run before the DDL), so the whole block is a no-op and the
    index is created normally. On a database that already holds the rows, the
    reconciliation runs first and the index creation below cannot fail.
    """
    if not PRE_INDEX_RECONCILIATIONS:
        return ""
    lines = [
        "-- ── Pre-index reconciliations (see PRE_INDEX_RECONCILIATIONS) ──────────",
        "-- DML the SQLite chain performs before a DDL statement that would",
        "-- otherwise fail on the un-repaired rows. The generator cannot translate",
        "-- SQLite DML in general, so each one is hand-written, declared and",
        "-- digest-pinned above. Each is guarded on its table existing, so it is a",
        "-- no-op on a fresh database.",
    ]
    for entry in PRE_INDEX_RECONCILIATIONS:
        lines.append("")
        table = index_tables[entry["index_name"]]
        lines.append(f"-- before: {entry['index_name']} (on {table})")
        lines.append("DO $oz_pre_index$")
        lines.append("BEGIN")
        lines.append(
            f"    IF to_regclass('public.{table}') IS NOT NULL THEN"
        )
        for stmt_line in entry["sql"].splitlines():
            lines.append("        " + stmt_line if stmt_line else "")
        lines.append("    END IF;")
        lines.append("END")
        lines.append("$oz_pre_index$;")
    return "\n".join(lines)


def render_obsolete_indexes() -> str:
    """Guarded DROPs for indexes a later SQLite migration removed."""
    lines = [
        "-- ── Indexes removed from the SQLite chain ─────────────────────────────",
        "-- This script only ever says CREATE … IF NOT EXISTS, so a database built",
        "-- before the removal keeps these forever. Dropping is the only way to",
        "-- converge an existing database on the current schema.",
    ]
    for name in sorted(OBSOLETE_PG_INDEXES):
        lines.append(f"DROP INDEX IF EXISTS {name};  -- removed by {OBSOLETE_PG_INDEXES[name]}")
    return "\n".join(lines)


def render() -> tuple[str, int, int, int, list[str]]:
    ids = registry_ids()
    db = build_db(ids)

    tables: list[tuple[str, set[str], str]] = []
    for name, sql in db.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY rowid"
    ):
        refs = set(re.findall(r'REFERENCES\s+"?(\w+)"?\s*\(', sql))
        tables.append((name, refs, convert_table(sql)))
    ordered = topo_sort(tables)

    indexes: list[str] = []
    unique_by_table: dict[str, list[str]] = defaultdict(list)
    skipped: list[str] = []
    # C38: every emitted index name -> the table it belongs to, so a declared
    # pre-index reconciliation can guard on its table existing.
    index_tables: dict[str, str] = {}
    for name, tbl, sql in db.execute(
        "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' "
        "AND sql IS NOT NULL ORDER BY name"
    ):
        if name in SQLITE_ONLY_INDEXES:
            skipped.append(name)
            continue
        s = re.sub(
            r"^CREATE (UNIQUE )?INDEX (?!IF NOT EXISTS)",
            r"CREATE \1INDEX IF NOT EXISTS ",
            sql,
        )
        s = s.rstrip().rstrip(";") + ";"
        # UNIQUE indexes must exist BEFORE any table whose FK references
        # their columns (composite FKs target them, and PG validates at
        # CREATE TABLE time) — emit each table's unique indexes directly
        # after that table in the topological loop.
        index_tables[name] = tbl
        if s.upper().startswith("CREATE UNIQUE INDEX"):
            unique_by_table[tbl].append(s)
        else:
            indexes.append(s)

    dumped_triggers = [
        r[0]
        for r in db.execute(
            "SELECT name FROM sqlite_master WHERE type='trigger' ORDER BY name"
        )
    ]
    missing = [t for t in dumped_triggers if t not in TRIGGER_MAP]
    stale = [t for t in TRIGGER_MAP if t not in dumped_triggers]
    if missing or stale:
        parts = []
        if missing:
            parts.append(f"no plpgsql port: {', '.join(missing)}")
        if stale:
            parts.append(f"stale TRIGGER_MAP entries: {', '.join(stale)}")
        raise SystemExit("error: trigger parity broken — " + "; ".join(parts))

    # C43: the membership check above is NAME-ONLY and can never prove the port
    # means the same thing as the SQLite trigger it mirrors. This is the
    # compensating control — declared evidence plus a body digest.
    check_trigger_verification(TRIGGER_MAP, TRIGGER_VERIFICATION, ROOT)
    check_pre_index_reconciliations(PRE_INDEX_RECONCILIATIONS, set(index_tables), ROOT)

    ordered_names = [name for name, _, _ in ordered]
    seeds = dump_seeds(db, ordered_names)
    specs = pg_column_specs(db, ordered_names)
    db.close()

    # Order matters: drop the obsolete indexes, then replay the renames (a
    # rename preserves rows; letting the reconciliation add the new column
    # instead would leave the legacy NOT NULL column behind), then reconcile
    # the remaining columns. All three are guarded, so a fresh database runs
    # them as no-ops before the DDL below creates everything.
    table_renames, column_renames = schema_evolution_ops()

    out: list[str] = [HEADER.rstrip(), ""]
    out.extend([render_obsolete_indexes(), ""])
    out.extend([render_evolution_ops(table_renames, column_renames), ""])
    out.extend([render_reconciliation(specs), ""])
    # C38: a declared reconciliation must run BEFORE the DDL that creates its
    # index, and the index is emitted with its table in the topological loop
    # below — so this block precedes the whole DDL section.
    pre_index = render_pre_index_reconciliations(index_tables)
    if pre_index:
        out.extend([pre_index, ""])
    for name, _refs, stmt in ordered:
        out.extend([stmt, ""])
        for idx in unique_by_table.get(name, []):
            out.extend([idx, ""])
    for trig in sorted(TRIGGER_MAP):
        out.extend([TRIGGER_MAP[trig], ""])
    for idx in indexes:
        out.extend([idx, ""])
    for seed in seeds:
        out.extend([seed, ""])
    out.extend([dump_rls(build_db(ids)), ""])

    return "\n".join(out).replace("\n", "\r\n") + "\n", len(ordered), len(indexes), len(seeds), skipped


def main(argv: list[str]) -> int:
    check = "--check" in argv
    if "--self-test" in argv:
        _self_test_rls_gate()
        _self_test_trigger_gate()
        _self_test_pre_index_gate()
        return 0
    body, n_tables, n_indexes, n_seeds, skipped = render()

    # Determinism self-proof: a second independent migration run must
    # render byte-identical output (this is what makes --check honest).
    body2, *_ = render()
    if body != body2:
        print("error: generator output is not deterministic across runs", file=sys.stderr)
        return 1

    if check:
        committed = DST.read_text(encoding="utf-8").replace("\r\n", "\n")
        if committed == body.replace("\r\n", "\n"):
            print(f"ok: {DST.name} matches the generator ({n_tables} tables, "
                  f"{n_indexes} indexes, {n_seeds} seed inserts)")
            return 0
        gen_lines = body.replace("\r\n", "\n").splitlines()
        com_lines = committed.splitlines()
        diff = sum(1 for a, b in zip(gen_lines, com_lines) if a != b)
        diff += abs(len(gen_lines) - len(com_lines))
        print(
            f"error: {DST.name} has drifted from the generator ({diff} differing "
            "lines; generated is authoritative). Never hand-edit the PG file — "
            "run: python3 scripts/generate-pg-migration.py\n"
            "If the drift is in a trigger, port the plpgsql in TRIGGER_MAP first.",
            file=sys.stderr,
        )
        return 1

    DST.write_text(body, encoding="utf-8", newline="")
    print(f"wrote {DST} ({n_tables} tables, {n_indexes} indexes, {n_seeds} seed inserts)")
    if skipped:
        print("skipped PG-incompatible indexes (SQLite-only): " + ", ".join(sorted(skipped)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
