#!/usr/bin/env bash
# ── test-records-index-escaping.sh ─────────────────────────────────────────
# Proves the cell sanitizer in scripts/generate-records-index.mjs actually bites.
# House precedent: test-eol-guard.sh / test-typecheck-gate.sh — drive the LIVE
# guard in a throwaway directory, never a copy of its logic.
#
# The generator is pointed at a temp tree through KASIRMU_RECORDS_ROOT, so its
# write-mode happens under $TMPDIR: docs/records/README.md is never touched,
# staged or regenerated by this script.
#
# Four assertions run twice: against the working-tree generator (must pass) and
# against a frozen deliberately-unfixed generator (must fail the exploit
# assertion, or the green run proves nothing).
#
# The unfixed stand-in is written by this script, not read from a commit. It
# used to be `git show HEAD:` and that leg was unsatisfiable by construction:
# the fix and this test shipped in one commit (c85bae9ef), so HEAD was already
# fixed from the next commit on.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/records-esc.XXXXXX")"
pass=0; fail=0; red=0
ok()  { echo "  ok   $1"; pass=$((pass+1)); }
bad() { echo "  FAIL $1"; fail=$((fail+1)); }

# An UNESCAPED label closer followed by (target) is what turns text into a link;
# the escaped form JOURNAL\](x) renders literally and is exactly what we want.
has_raw_link_to() { grep -qE "(^|[^\\])\]\($1\)" "$2"; }

docs() {
  local base="$1"
  mkdir -p "$base/docs/records" "$base/docs/decisions" "$base/docs/observability" "$base/scripts"
  {
    echo "# ADR #99: JOURNAL](JOURNAL-TAMPERED.md) tamper probe"
    echo
    echo '**Status:** Implemented (2026-07-19) see [link](JOURNAL-TAMPERED.md)'
  } > "$base/docs/records/hostile.md"
  {
    echo '---'
    echo 'num: 7'
    echo 'title: "A clean [title] with (parens) and a |pipe|"'
    echo 'status: Accepted'
    echo 'area: sync'
    echo '---'
    echo '# this body heading must never become the title'
  } > "$base/docs/records/clean.md"
  { printf '# ADR #98: '; printf 'x%.0s' $(seq 1 300); printf '\n'; } > "$base/docs/records/long.md"
}

assert_fixed() {
  local label="$1" idx="$2/docs/records/README.md"
  if has_raw_link_to "JOURNAL-TAMPERED\.md" "$idx"; then
    bad "$label: an unescaped link to a non-existent file was emitted"
  else
    ok "$label: no unescaped link to a non-existent file"
  fi
  if grep -qF "JOURNAL\]" "$idx"; then
    ok "$label: the stray label closer survives, escaped"
  else
    bad "$label: the label closer was neither escaped nor kept"
  fi
  if grep -qF "A clean title with (parens) and a \|pipe\|" "$idx"; then
    ok "$label: front-matter title wins; brackets and pipes escaped, parens untouched"
  else
    bad "$label: clean row missing, title wrong, or escaping not applied"
  fi
  if grep -qF '…' "$idx" && ! awk 'length($0) > 300 { bad = 1 } END { exit bad }' "$idx"; then
    ok "$label: the 300-char heading is capped and no row runs unbounded"
  else
    bad "$label: no length cap on the 300-char heading"
  fi
}

red_reproduced() {
  local idx="$1/docs/records/README.md"
  if [ ! -f "$idx" ]; then bad "the unfixed fixture produced no index at all"; return; fi
  if has_raw_link_to "JOURNAL-TAMPERED\.md" "$idx"; then
    ok "the frozen unfixed generator emits the fabricated link — the bug is real, this guard bites"
    red=1
  else
    bad "the frozen unfixed generator did not reproduce the exploit; the green run proves nothing"
  fi
}

echo "=== working-tree generator (the fix under test) ==="
docs "$TMP/after"
KASIRMU_RECORDS_ROOT="$TMP/after" node "$ROOT/scripts/generate-records-index.mjs" >/dev/null 2>&1
assert_fixed "fixed" "$TMP/after"
if KASIRMU_RECORDS_ROOT="$TMP/after" node "$ROOT/scripts/generate-records-index.mjs" --check >/dev/null 2>&1; then
  ok "fixed: --check agrees with its own output and the href-existence leg passes"
else
  bad "fixed: --check failed on a tree the generator just wrote"
fi

echo "=== frozen UNFIXED generator, same fixture (expected RED) ==="
# This leg used to read the generator from `git show HEAD:`. That could only
# ever work in the window between writing the fix and committing it: the fix
# and this test landed in the SAME commit (c85bae9ef), so from the very next
# commit onward HEAD already held the fixed generator, the exploit could not be
# reproduced, and the whole run failed with "the green run proves nothing" --
# a control that is unsatisfiable by construction. The unfixed shape is frozen
# below instead. It is deliberately NOT a copy of the live generator: it is the
# naive shape the live one was fixed away from (a scraped heading dropped raw
# into a link label), and its only job is to prove the assertions above can
# fire. If the live generator ever loses its escaping, `assert_fixed` catches
# that on the working tree; this leg catches the opposite failure, a suite of
# assertions that could not have failed.
docs "$TMP/before"
cat > "$TMP/before/scripts/generate-records-index.mjs" <<'UNFIXED_JS'
// Frozen, deliberately-unfixed stand-in. No mdCell(): the heading goes into the
// label verbatim, which is the exploit the escaping fix closed.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = join(process.env.KASIRMU_RECORDS_ROOT, 'docs', 'records');
const rows = readdirSync(dir)
  .filter((f) => f.endsWith('.md') && f !== 'README.md')
  .sort()
  .map((f) => {
    const heading = readFileSync(join(dir, f), 'utf8').match(/^#\s+(.*)$/m);
    const title = heading ? heading[1] : f;
    return '| [' + title + '](' + f + ') |';
  });
writeFileSync(join(dir, 'README.md'), ['| Document |', '| --- |'].concat(rows).join('\n') + '\n');
UNFIXED_JS
KASIRMU_RECORDS_ROOT="$TMP/before" node "$TMP/before/scripts/generate-records-index.mjs" >/dev/null 2>&1
red_reproduced "$TMP/before"

rm -rf "$TMP"
if [ -e "$TMP" ]; then bad "temp tree survived: $TMP"; else ok "temp tree removed, zero leftovers"; fi
echo "passed=$pass failed=$fail red_reproduced=$red"
if [ "$fail" -eq 0 ] && [ "$red" -eq 1 ]; then
  echo "ok: records-index escaping guard verified against the live generator"
  exit 0
fi
echo "error: escaping guard did not behave as expected"
exit 1
