#!/usr/bin/env bash
# ── test-records-index-escaping.sh ─────────────────────────────────────────
# Proves the cell sanitizer in scripts/generate-records-index.mjs actually bites.
# House precedent: test-eol-guard.sh / test-typecheck-gate.sh — drive the LIVE
# guard in a throwaway directory, never a copy of its logic.
#
# The generator is pointed at a temp tree through KASIRMU_RECORDS_ROOT, so its
# write-mode happens under $TMPDIR: docs/records/README.md is never touched,
# staged or regenerated by this script.
#
# Four assertions run twice: against the working-tree generator (must pass) and
# against the committed HEAD copy (must fail the exploit assertion, or the green
# run proves nothing).
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/records-esc.XXXXXX")"
pass=0; fail=0; red=0
ok()  { echo "  ok   $1"; pass=$((pass+1)); }
bad() { echo "  FAIL $1"; fail=$((fail+1)); }

# An UNESCAPED label closer followed by (target) is what turns text into a link;
# the escaped form JOURNAL\](x) renders literally and is exactly what we want.
has_raw_link_to() { grep -qE "(^|[^\\])\]\($1\)" "$2"; }

docs() {
  local base="$1"
  mkdir -p "$base/docs/records" "$base/docs/decisions" "$base/docs/observability" "$base/scripts"
  {
    echo "# ADR #99: JOURNAL](JOURNAL-TAMPERED.md) tamper probe"
    echo
    echo '**Status:** Implemented (2026-07-19) see [link](JOURNAL-TAMPERED.md)'
  } > "$base/docs/records/hostile.md"
  {
    echo '---'
    echo 'num: 7'
    echo 'title: "A clean [title] with (parens) and a |pipe|"'
    echo 'status: Accepted'
    echo 'area: sync'
    echo '---'
    echo '# this body heading must never become the title'
  } > "$base/docs/records/clean.md"
  { printf '# ADR #98: '; printf 'x%.0s' $(seq 1 300); printf '\n'; } > "$base/docs/records/long.md"
}

assert_fixed() {
  local label="$1" idx="$2/docs/records/README.md"
  if has_raw_link_to "JOURNAL-TAMPERED\.md" "$idx"; then
    bad "$label: an unescaped link to a non-existent file was emitted"
  else
    ok "$label: no unescaped link to a non-existent file"
  fi
  if grep -qF "JOURNAL\]" "$idx"; then
    ok "$label: the stray label closer survives, escaped"
  else
    bad "$label: the label closer was neither escaped nor kept"
  fi
  if grep -qF "A clean title with (parens) and a \|pipe\|" "$idx"; then
    ok "$label: front-matter title wins; brackets and pipes escaped, parens untouched"
  else
    bad "$label: clean row missing, title wrong, or escaping not applied"
  fi
  if grep -qF '…' "$idx" && ! awk 'length($0) > 300 { bad = 1 } END { exit bad }' "$idx"; then
    ok "$label: the 300-char heading is capped and no row runs unbounded"
  else
    bad "$label: no length cap on the 300-char heading"
  fi
}

red_reproduced() {
  local idx="$1/docs/records/README.md"
  if [ ! -f "$idx" ]; then bad "HEAD fixture produced no index at all"; return; fi
  if has_raw_link_to "JOURNAL-TAMPERED\.md" "$idx"; then
    ok "HEAD copy emits the fabricated link — the bug is real, this guard bites"
    red=1
  else
    bad "HEAD copy did not reproduce the exploit; the green run proves nothing"
  fi
}

echo "=== working-tree generator (the fix under test) ==="
docs "$TMP/after"
KASIRMU_RECORDS_ROOT="$TMP/after" node "$ROOT/scripts/generate-records-index.mjs" >/dev/null 2>&1
assert_fixed "fixed" "$TMP/after"
if KASIRMU_RECORDS_ROOT="$TMP/after" node "$ROOT/scripts/generate-records-index.mjs" --check >/dev/null 2>&1; then
  ok "fixed: --check agrees with its own output and the href-existence leg passes"
else
  bad "fixed: --check failed on a tree the generator just wrote"
fi

echo "=== committed HEAD copy, same fixture (expected RED) ==="
docs "$TMP/before"
git -C "$ROOT" show HEAD:scripts/generate-records-index.mjs > "$TMP/before/scripts/generate-records-index.mjs" 2>/dev/null
KASIRMU_RECORDS_ROOT="$TMP/before" node "$TMP/before/scripts/generate-records-index.mjs" >/dev/null 2>&1
red_reproduced "$TMP/before"

rm -rf "$TMP"
if [ -e "$TMP" ]; then bad "temp tree survived: $TMP"; else ok "temp tree removed, zero leftovers"; fi
echo "passed=$pass failed=$fail red_reproduced=$red"
if [ "$fail" -eq 0 ] && [ "$red" -eq 1 ]; then
  echo "ok: records-index escaping guard verified against the live generator"
  exit 0
fi
echo "error: escaping guard did not behave as expected"
exit 1
