/**
 * Brand-asset integrity — every manifest path resolves, and every tenant is
 * complete.
 *
 * `assets/branding/<tenant>/manifest.json` is an INPUT: `scripts/sync-branding.ps1`
 * reads its `assets.*` paths and copies from them. A path that points at a file
 * which no longer exists is therefore not a cosmetic doc error — the sync either
 * skips the asset (leaving the previous brand's file in the destination) or exits
 * non-zero. Nothing compared the manifest to the tree, so this could sit broken
 * until someone ran a sync for that tenant.
 *
 * These assertions read the manifests and the filesystem only; they never invoke
 * PowerShell, so they run anywhere the ui tests run.
 */

import fs from 'fs';
import path from 'path';
import { describe, it, expect } from 'vitest';

const BRANDING_DIR = path.resolve(process.cwd(), '../assets/branding');

/** Tenants the sync script is expected to be able to serve. */
const TENANTS = ['default', 'acme-tenant', 'beta-retail'] as const;

interface BrandManifest {
  brandId: string;
  appName: string;
  companyName: string;
  themeTokens: { primaryHsl: string; accentHsl: string; fontFamily: string };
  assets: Record<string, Record<string, string>>;
}

function readManifest(tenant: string): BrandManifest {
  const raw = fs.readFileSync(path.join(BRANDING_DIR, tenant, 'manifest.json'), 'utf8');
  return JSON.parse(raw) as BrandManifest;
}

/** Every leaf path in the manifest's `assets` map, flattened. */
function assetPaths(manifest: BrandManifest): Array<{ group: string; key: string; value: string }> {
  const out: Array<{ group: string; key: string; value: string }> = [];
  for (const [group, entries] of Object.entries(manifest.assets)) {
    for (const [key, value] of Object.entries(entries)) {
      out.push({ group, key, value });
    }
  }
  return out;
}

describe('brand manifests resolve to real files', () => {
  it.each(TENANTS)('%s declares a well-formed manifest', (tenant) => {
    const manifest = readManifest(tenant);
    expect(manifest.brandId, `${tenant} brandId`).toBe(tenant);
    expect(manifest.appName, `${tenant} appName`).toBeTruthy();
    expect(manifest.companyName, `${tenant} companyName`).toBeTruthy();
    // The three token shapes the sync script interpolates into brand-tokens.css.
    expect(manifest.themeTokens.primaryHsl, `${tenant} primaryHsl`).toMatch(/^\d+,\s*\d+%,\s*\d+%$/);
    expect(manifest.themeTokens.accentHsl, `${tenant} accentHsl`).toMatch(/^\d+,\s*\d+%,\s*\d+%$/);
    expect(manifest.themeTokens.fontFamily, `${tenant} fontFamily`).toBeTruthy();
  });

  it.each(TENANTS)('%s asset paths all exist on disk', (tenant) => {
    const manifest = readManifest(tenant);
    const missing = assetPaths(manifest)
      .filter(({ value }) => value !== '')
      .filter(({ value }) => !fs.existsSync(path.join(BRANDING_DIR, tenant, value)))
      .map(({ group, key, value }) => `${group}.${key} -> ${value}`);
    expect(missing, `${tenant} manifest points at missing file(s)`).toEqual([]);
  });

  it.each(TENANTS)('%s hardware README matches the generator template', (tenant) => {
    // The README is generated by sync-branding.ps1, which now rewrites it when the
    // content differs. This asserts the committed file is the generated one — the
    // check that would have caught `receipt` having become `eceipt` and the fence
    // losing two of its three backticks.
    const readme = fs.readFileSync(path.join(BRANDING_DIR, tenant, 'hardware/README.md'), 'utf8');
    expect(readme, `${tenant} hardware README lost the a in assets/`).toContain('assets/source-icon.png');
    expect(readme, `${tenant} hardware README has a truncated filename`).not.toMatch(/(?<!re)ceipt-logo/);
    // Three backticks, not one: the header fence carries a language tag.
    expect(readme, `${tenant} hardware README fence is malformed`).toContain('```powershell');
    expect(readme, `${tenant} hardware README has an unclosed code fence`).toMatch(/```powershell[\s\S]*\n```\s*$/);
  });
});

describe('the tenant template is usable', () => {
  it('example-tenant declares a manifest the sync script can read', () => {
    const templateDir = path.join(BRANDING_DIR, 'whitelabel/example-tenant');
    expect(fs.existsSync(path.join(templateDir, 'manifest.json'))).toBe(true);
    const manifest = JSON.parse(fs.readFileSync(path.join(templateDir, 'manifest.json'), 'utf8')) as BrandManifest;
    expect(manifest.brandId).toBeTruthy();
    expect(manifest.assets).toBeTruthy();
  });

  it('example-tenant ships every subdirectory the sync script copies from', () => {
    // A template missing one of these produces a tenant whose sync silently skips
    // that asset group, so the previous brand's file stays in the destination.
    const templateDir = path.join(BRANDING_DIR, 'whitelabel/example-tenant');
    for (const dir of ['vector', 'web', 'desktop', 'hardware']) {
      expect(fs.existsSync(path.join(templateDir, dir)), `template is missing ${dir}/`).toBe(true);
    }
  });
});

describe('the branding README explains the model', () => {
  it('exists and states the origin rule', () => {
    const readmePath = path.join(BRANDING_DIR, 'README.md');
    expect(fs.existsSync(readmePath), 'assets/branding/README.md is missing').toBe(true);
    const readme = fs.readFileSync(readmePath, 'utf8');
    // Anchor the two facts a reader must not miss: the directory is the origin,
    // and its copies are overwritten.
    expect(readme).toMatch(/origin/i);
    expect(readme).toMatch(/sync-branding\.ps1/);
  });
});
