//! GENERATED by the registration-gate sweep - DO NOT HAND-EDIT. //!
//!
//! Every registered command this shell gate-accepts is absent from this file;
//! everything it does not accept appears once, with the measured state:
//! "no_session_resolution" (the wrapper never resolves a session) or
//! "resolves_session_names_no_permission" (it resolves one and asks nobody whether
//! the caller may - authenticate-then-assume).

//! Regenerate rather than type: see the header of registration_gate_tests.rs.
//! A hand-edited line here is the drift this generated file exists to prevent.

/// The measured debt ledger: (registered name, state).
pub const DEBT_LEDGER: &[(&str, &str)] = &[
    ("auth::staff_login", "no_session_resolution"),
    ("auth::staff_check_username", "no_session_resolution"),
    (
        "auth::create_session",
        "resolves_session_names_no_permission",
    ),
    (
        "auth::destroy_session",
        "resolves_session_names_no_permission",
    ),
    (
        "auth::session_keepalive",
        "resolves_session_names_no_permission",
    ),
    ("auth::list_organizations", "no_session_resolution"),
    (
        "auth::switch_organization",
        "resolves_session_names_no_permission",
    ),
    ("branding::get_brand_settings", "no_session_resolution"),
    (
        "branding::set_brand_primary_colour",
        "no_session_resolution",
    ),
    ("branding::set_brand_logo_path", "no_session_resolution"),
    ("branding::set_brand_store_name", "no_session_resolution"),
    ("staff::bootstrap_owner", "no_session_resolution"),
    (
        "subscription::get_subscription_capabilities",
        "no_session_resolution",
    ),
    ("categories::list_categories", "no_session_resolution"),
    ("currencies::currency_info", "no_session_resolution"),
    ("currencies::get_default_currency", "no_session_resolution"),
    ("currencies::set_default_currency", "no_session_resolution"),
    ("features::list_all_features", "no_session_resolution"),
    (
        "features::list_all_features_scoped",
        "resolves_session_names_no_permission",
    ),
    ("health::ping", "no_session_resolution"),
    ("health::version", "no_session_resolution"),
    ("health::get_device_id", "no_session_resolution"),
    ("health::get_local_ip", "no_session_resolution"),
    (
        "pos::add_line_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "pos::complete_sale_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "pos::complete_sale_with_resolved_shortfalls_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "pos::override_cart_deduction_location_scoped",
        "resolves_session_names_no_permission",
    ),
    ("pos::get_cart_deduction_location", "no_session_resolution"),
    (
        "pos::get_cart_deduction_location_scoped",
        "resolves_session_names_no_permission",
    ),
    ("history::list_sales", "no_session_resolution"),
    ("history::get_sale", "no_session_resolution"),
    ("history::export_daily_summary", "no_session_resolution"),
    ("history::export_sales_by_hour", "no_session_resolution"),
    ("history::export_eod_report", "no_session_resolution"),
    ("settings::get_receipt_settings", "no_session_resolution"),
    ("settings::get_store_settings", "no_session_resolution"),
    ("settings::get_credit_settings", "no_session_resolution"),
    ("settings::get_hardware_settings", "no_session_resolution"),
    (
        "settings::get_user_preferences_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "settings::set_user_preferences_scoped",
        "resolves_session_names_no_permission",
    ),
    ("settings::get_setting", "no_session_resolution"),
    ("settings::gateway_status", "no_session_resolution"),
    ("settings::set_setting", "no_session_resolution"),
    ("setup::get_enabled_features", "no_session_resolution"),
    ("setup::complete_setup", "no_session_resolution"),
    ("setup::dismiss_setup_wizard", "no_session_resolution"),
    ("browser::open_product_images", "no_session_resolution"),
    ("setup::get_setup_status", "no_session_resolution"),
    ("workspaces::list_workspaces", "no_session_resolution"),
    (
        "workspaces::list_workspace_screens",
        "no_session_resolution",
    ),
    ("workspaces::resolve_boot_store", "no_session_resolution"),
    ("sync::test_sync_connection", "no_session_resolution"),
    (
        "refunds::process_refund_scoped",
        "resolves_session_names_no_permission",
    ),
    ("scale::read_scale_weight", "no_session_resolution"),
    (
        "branding::get_brand_settings_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "branding::set_brand_logo_path_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "branding::set_brand_primary_colour_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "branding::set_brand_store_name_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "categories::list_categories_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "hardware::stop_scanner_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "hardware::list_displays_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "hardware::display_show_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "hardware::display_clear_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "hardware::discover_hardware_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "offline::enqueue_offline_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "offline::list_pending_offline_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "offline::list_remote_failures_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "offline::pending_offline_count_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "products::adjust_stock_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "products::get_product_track_serial_batch_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "products::get_product_track_serial_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "products::list_products_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "products::list_warehouse_products_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "products::lookup_by_barcode_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "products::lookup_product_by_sku_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "products::record_product_search_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "promotions::get_promotion_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "promotions::get_sale_promotions_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "promotions::list_promotions_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "scale::list_scale_devices_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "scale::read_scale_weight_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "sync::get_sync_settings_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "tables::get_table_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "tables::list_sections_scoped",
        "resolves_session_names_no_permission",
    ),
    (
        "tables::list_tables_scoped",
        "resolves_session_names_no_permission",
    ),
];

/// Registered commands the sweep found today. The floor in
/// registration_gate_tests.rs is asserted equal to this, so a regenerated ledger
/// that disagrees with a hand-kept floor fails the build.
pub const REGISTERED_TOTAL: usize = 320;

/// Debt entries today: the ceiling the ledger may only shrink under.
///
/// Lowered from 125 by the terminals F-017 pass: four `terminals::*` reads
/// (`get_terminal_scoped`, `list_terminal_overrides_scoped`,
/// `list_terminals_scoped`, `ping_terminal_scoped`) stopped being
/// authenticate-then-assume when each gained the session-derived
/// `TERMINALS_READ` gate its `kasirmu_bridge` twin already enforced.
///
/// Lowered from 90 by the hardware F-017 pass: `hardware::open_cash_drawer_scoped`
/// stopped being authenticate-then-assume when it gained the `PAYMENTS_CASH`
/// gate its `kasirmu_bridge::hardware` twin already enforced under the same finding
/// number. It is the only one of the seven `hardware::*` rows with a gate to
/// copy — the other six are ungated in the bridge too, so they stay as debt
/// until an owner rules on what permission they should carry.
///
/// Lowered from 88 by the memo tablet-delegation: `memo::list_active_memos_scoped`
/// and `memo::acknowledge_memo_scoped` stopped being authenticate-then-assume when
/// their bodies became `kasirmu_bridge::memo` shims (the bridge module names
/// `permissions::`), and `hardware::list_scanners_scoped` was swept out as stale
/// debt: commit `cde2c8ac2` added a quoted-`domain:action` literal to bridge
/// `hardware.rs` after this ledger was last generated, which flipped the sweep's
/// merge classification for that name. No permission was added to the command; the
/// row described a state the tree no longer measures, and the ratchet printed it
/// as the correction.
pub const DEBT_CEILING: usize = 85;

/// Lowered from 89 by T11: `settings::set_hardware_settings` shed its row by deletion,
/// not by gating. Its only argument beyond the DTO was a renderer-supplied `user_id` --
/// the actor the permission check asks about -- and the session-scoped twin was already
/// registered, so once the UI stopped naming the unscoped door (`7b756b9c7`) the shell
/// kept the one that derives identity from the session and dropped the one that took it
/// on faith. This retires a REGISTERED command, which `scripts/retire-legacy-commands.py`
/// refuses to do by design: it deletes unregistered leftovers, and a live door needs the
/// call sites moved first.
///
/// Names that never resolve a session at all.
pub const NO_SESSION_RESOLUTION: usize = 41;

/// Authenticate-then-assume: a session is resolved and no permission asked.
/// 44 + 41 = 85 = `DEBT_CEILING`, as the class counts must sum to the ledger.
pub const RESOLVES_SESSION_NAMES_NO_PERMISSION: usize = 44;

/// Registered names whose wrapper body the generator could not find (must be 0).
pub const UNSOURCED: usize = 0;
