/// <reference types="vitest/config" />
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath, URL } from 'node:url';
import { buildIdDefine } from './src/build-id.node';

// Tauri expects a fixed port; fail if it isn't available.
const host = process.env.TAURI_DEV_HOST;

export default defineConfig(({ command }) => ({
  plugins: [react()],

  // Stamps the commit this bundle was built from, so two builds of the same
  // release can be told apart. See `src/build-id.ts`.
  define: buildIdDefine(),

  resolve: {
    // Use the explicit regex form for the `@/` alias (instead of the
    // shorthand `'@': path`). The shorthand is honored by Vite's
    // dev/build resolver but NOT by Vitest 1.6.x's pool-worker
    // resolver — imports like `@/components/Badge` fall through to
    // Node's ESM resolver and fail with `Cannot find package`.
    // Trailing slashes on both `./src/` and `replacement` keep the
    // path join clean (`…/foo`, never `…/srccomponents/foo`).
    //
    // The Tauri API mocks are DEV-SERVER-ONLY: they let the app be
    // previewed in a plain browser (and drive E2E) without the Rust
    // backend. They must never be bundled into production builds —
    // `vite build` (packaged app) resolves the real @tauri-apps/api
    // packages, otherwise the shipped app silently runs on mock data.
    // Inside a real Tauri webview (packaged app or `tauri dev`) the
    // mock itself delegates to window.__TAURI_INTERNALS__, so the dev
    // server still talks to the real backend when one is present.
    alias: [
      ...(command === 'serve'
        ? [
            {
              find: /^@tauri-apps\/api\/core$/,
              replacement: `${fileURLToPath(new URL('./src/dev-mock/tauri-api.ts', import.meta.url))}`,
            },
            {
              // Dev event bridge — the real @tauri-apps/api/event module needs
              // window.__TAURI_INTERNALS__ (undefined in a plain browser) and
              // crashes the KDS screen's kds:orders-changed listener. The mock
              // provides in-memory pub/sub so E2E dev flows work end to end.
              find: /^@tauri-apps\/api\/event$/,
              replacement: `${fileURLToPath(new URL('./src/dev-mock/tauri-event.ts', import.meta.url))}`,
            },
          ]
        : []),
      // Tier-badge artwork is generated by scripts/generate-tier-badges.ps1 into
      // assets/tier-badges/svg/, outside this package — the same out-of-package
      // shape as the Fluent corpus below, and for the same reason. Copying it
      // into ui/ instead would create a duplicate that a palette change could
      // silently leave stale, which is the failure assets/branding/README.md
      // states as its one rule. `@tier-badges/` does not start with `@/`, so
      // this entry cannot be shadowed by the generic rule below either way.
      {
        find: /^@tier-badges\//,
        replacement: fileURLToPath(new URL('../assets/tier-badges/svg/', import.meta.url)),
      },
      // P9a: the Fluent corpus no longer lives under ui/. It is plain data that any
      // toolkit can consume (Fluent ships Rust bindings too), so it sits at
      // shared-ui/locales/ beside the repo root. This entry MUST precede the generic
      // `@/` rule below — Vite/rollup take the first matching alias, so `@/locales/…`
      // would otherwise resolve to ./src/locales/ and every one of the `?raw`
      // imports would fail to resolve.
      {
        find: /^@\/locales\//,
        replacement: `${fileURLToPath(new URL('../shared-ui/locales/', import.meta.url))}`,
      },
      {
        find: /^@\//,
        replacement: `${fileURLToPath(new URL('./src/', import.meta.url))}/`,
      },
    ],
  },

  // Vite options tailored for Tauri development.
  clearScreen: false,

  // ── Build: vendor chunking + code-splitting (PERF-05) ─────────────
  // Lazy-loaded routes (PERF-01) already split feature screens into
  // per-route chunks. manualChunks additionally isolates the heavy
  // vendor libraries so their long-lived cache stays stable and the
  // entry bundle stays small.
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-react': ['react', 'react-dom'],
          'vendor-fluent': ['@fluent/bundle', '@fluent/react'],
          'vendor-charts': ['recharts'],
          'vendor-search': ['fuse.js'],
          'vendor-window': ['react-window'],
        },
      },
    },
    // The recharts vendor chunk legitimately exceeds Vite's default 500 kB
    // raw threshold; real enforcement lives in scripts/check-bundle.mjs
    // (PERF-02), which measures gzip against explicit budgets.
    chunkSizeWarningLimit: 600,
  },

  server: {
    port: 1420,
    strictPort: true,
    // P9a: the Fluent corpus sits at shared-ui/locales/, OUTSIDE this package, so the
    // dev server and Vitest both refuse to serve it ("Denied ID …/shared.ftl?raw")
    // unless it is allowed here. Naming an entry REPLACES Vite's default (the
    // workspace root), so the package root is listed too.
    fs: {
      allow: [
        fileURLToPath(new URL('.', import.meta.url)),
        fileURLToPath(new URL('../shared-ui', import.meta.url)),
        // The generated tier badges, aliased as `@tier-badges/` above. Outside
        // this package, so the dev server refuses to serve it unless named here.
        fileURLToPath(new URL('../assets/tier-badges', import.meta.url)),
      ],
    },
    host: host || false,
    hmr: host
      ? { protocol: 'ws', host, port: 1421 }
      : undefined,
    watch: {
      // Tell vite to ignore watching `apps/` so the Rust change
      // watcher doesn't trigger a Vite reload.
      ignored: ['**/apps/**'],
    },
  },

  test: {
    // ── Pool ─────────────────────────────────────────────────────────────
    // worker_threads instead of child_process forks: lower per-worker
    // overhead than forks, and they are what lets maxWorkers be capped
    // without paying process-spawn cost on the next file.
    //
    // maxWorkers is CAPPED, and the cap is measured rather than assumed.
    // Left unset, Vitest sizes the pool from the host CPU count, so on this
    // 32-thread machine it ran ~27 workers at once. Every worker keeps a full
    // jsdom window plus the module graph it imported, and this suite has 610
    // test files, so the ceiling is how many the pool will start at once.
    //
    // WHAT JUSTIFIES THIS IS THE CONTENDED RUN, not the solitary one, and the
    // round that established it had to discard two earlier answers first — both
    // are recorded here because each one looked right at the time.
    //
    // Mistake 1 — unattributed memory. Sampling Get-Process node counts EVERY
    // node on the box. This machine idles at ~20 node processes and ~2.0 GB
    // from Adobe Creative Cloud, the DSH harness, an Astro dev server and an
    // npm dev run, so the first pass reported a "7.5 GB peak" that was never
    // vitest's.
    // Mistake 2 — measuring an idle machine. A cap can only pay for itself
    // under the load it exists to survive, and a solitary run never produces
    // that load. Solo, the comparison was "uncapped ~80s / capped ~160s", which
    // made the cap look like a pure loss.
    //
    // The experiment that decides it: TWO FULL SUITES AT ONCE, which is this
    // checkout's normal state (other agent sessions run here constantly).
    // Measured 2026-10-07, wall-clock and low-water free memory for the pair:
    //   uncapped (--maxWorkers=32)   26 and 13 test failures   low free 2855 MB   217s
    //   capped   (this file)          9 and  9 test failures   low free 8506 MB   156s
    // The differences are not noise and not about speed:
    //   * 9/9 is EXACTLY the solitary baseline, so under the cap the pair
    //     produces ZERO contention-induced failures. Uncapped it produced 39.
    //   * The extra failures are starvation, not defects — e.g.
    //     useNewTicketSound "Hook timed out in 5000ms", plus AppShell,
    //     ConfirmDialog, FastPINOverlay and SubscriptionContext. Every one of
    //     them passes on its own.
    //   * The cap is FASTER on the contended pair (156s vs 217s), because work
    //     that starves does not finish.
    // So: cap for correctness under contention. Speed on an idle machine is not
    // the property being optimised, and a solitary run is not the measurement
    // that justifies or condemns it.
    //
    // 16 rather than 8 because 8 measured no better and ~15s slower. Re-measure
    // with the CONTENDED pair before changing it. For a one-off run:
    //   npx vitest run --maxWorkers=32
    maxWorkers: 16,
    minWorkers: 2,
    // maxConcurrency stays at its default: it bounds tests per worker, and
    // the files-with-many-tests case it was added for is already served by
    // the worker cap above.
    pool: 'threads',
    fileParallelism: true,

    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test-setup.ts'],
    css: false,

    // Exclude Playwright e2e tests (run via `npm run test:e2e`) and
    // node_modules package tests picked up by the broad glob.
    exclude: ['e2e/**', 'node_modules/**'],

    // Per-test timeout (ms). Default 5000 is fine for most tests;
    // DataManagementScreen (55 tests, ~225ms each) is the heaviest
    // file and stays well within this budget. Bumped to 10s for CI
    // headroom on slow runners.
    testTimeout: 10_000,

    // Per-hook timeout (ms) for beforeEach / afterEach. Default 5000
    // is generous — no test file has hooks that take longer.
    hookTimeout: 5_000,

    // ── Coverage ────────────────────────────────────────────────────────
    //
    // Run with `npm run test:coverage` (or `vitest run --coverage`).
    // Uses the v8 provider (native to Node; faster than istanbul).
    // HTML + JSON reports land in `../coverage/ui/` so they sit beside
    // the Rust coverage report produced by `scripts/coverage.{sh,ps1}`.
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'json', 'json-summary', 'lcov'],
      reportsDirectory: '../coverage/ui',
      // Only count source files — never the test code itself.
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        '**/node_modules/**',
        '**/*.test.{ts,tsx}',
        '**/__tests__/**',
        '**/test-setup.ts',
        '**/i18n/test-utils.tsx',
        // Type-only modules (Fluent locale bundles are just strings). Path-agnostic,
        // so it kept matching after P9a moved the corpus to shared-ui/locales/.
        '**/locales/**',
      ],
    },
  },
}));
